import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";
import bcrypt from "bcryptjs";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

const contracts = [
  {
    solicNumber: "FA8617-26-R-0001",
    title: "Cybersecurity Operations Center (CSOC) Support Services",
    agency: "Department of the Air Force",
    subAgency: "Air Force Life Cycle Management Center",
    description: "Provide 24/7 Cybersecurity Operations Center support including threat monitoring, incident response, vulnerability management, and security engineering for AFLCMC enterprise systems.",
    requirements: JSON.stringify(["CSSP certification", "DoD 8570.01-M compliant staff", "SIEM experience", "Clearance: Secret"]),
    naicsCode: "541519",
    setAside: "Unrestricted",
    valueMin: 45000000,
    valueMax: 75000000,
    dueDate: new Date("2026-06-15"),
    pob: "Wright-Patterson AFB, OH",
    securityClear: "Secret",
    type: "FFP",
  },
  {
    solicNumber: "W912DR-26-R-0045",
    title: "Installation Support Services — Fort Campbell",
    agency: "Department of the Army",
    subAgency: "Army Corps of Engineers",
    description: "Comprehensive installation support services including facilities management, grounds maintenance, utilities operations, and base operations support at Fort Campbell, KY.",
    requirements: JSON.stringify(["Facilities management experience", "Army installation experience", "ISO 9001 certification preferred"]),
    naicsCode: "561210",
    setAside: "SB",
    valueMin: 12000000,
    valueMax: 18000000,
    dueDate: new Date("2026-05-30"),
    pob: "Fort Campbell, KY",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "N00189-26-R-Z001",
    title: "Naval Warfare Systems Integration & Test",
    agency: "Department of the Navy",
    subAgency: "Naval Supply Systems Command",
    description: "Systems integration, test, and evaluation support for naval warfare electronic systems including radar, EW, and C2 systems aboard surface combatants.",
    requirements: JSON.stringify(["Systems integration experience", "Navy platform experience", "TS/SCI clearance required", "DoD EVMS compliance"]),
    naicsCode: "541330",
    setAside: "Unrestricted",
    valueMin: 85000000,
    valueMax: 120000000,
    dueDate: new Date("2026-07-01"),
    pob: "Norfolk, VA",
    securityClear: "TS/SCI",
    type: "CPFF",
  },
  {
    solicNumber: "75N91026R00012",
    title: "Public Health Emergency Preparedness Staffing",
    agency: "Department of Health and Human Services",
    subAgency: "CDC Office of Preparedness",
    description: "Provide experienced public health professionals to support CDC emergency preparedness and response operations, epidemiology investigations, and surge capacity during declared emergencies.",
    requirements: JSON.stringify(["MPH or equivalent", "Emergency response experience", "Epidemiology background", "FEMA ICS certification"]),
    naicsCode: "621999",
    setAside: "8(a)",
    valueMin: 8000000,
    valueMax: 14000000,
    dueDate: new Date("2026-05-20"),
    pob: "Atlanta, GA",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "GS-35F-26R-0088",
    title: "Enterprise Cloud Migration & DevSecOps Services",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service",
    description: "Provide cloud migration strategy, DevSecOps implementation, and ongoing cloud operations for civilian agency customers under the GSA MAS program.",
    requirements: JSON.stringify(["FedRAMP experience", "AWS/Azure/GCP certifications", "DevSecOps toolchain expertise", "NIST 800-53 compliance"]),
    naicsCode: "541512",
    setAside: "Unrestricted",
    valueMin: 0,
    valueMax: 500000000,
    dueDate: new Date("2026-08-01"),
    pob: "Multiple Locations (Nationwide)",
    securityClear: "None",
    type: "IDIQ",
  },
  {
    solicNumber: "DTRA-26-R-00019",
    title: "Chemical & Biological Defense Research Support",
    agency: "Defense Threat Reduction Agency",
    subAgency: null,
    description: "Scientific and technical support for CBRN defense research programs, including lab analysis, modeling and simulation, and technical assessments of chemical and biological threats.",
    requirements: JSON.stringify(["PhD in relevant science field", "CBRN defense background", "TS/SCI clearance", "Biosafety Level 3 lab experience"]),
    naicsCode: "541715",
    setAside: "SDVOSB",
    valueMin: 22000000,
    valueMax: 35000000,
    dueDate: new Date("2026-06-28"),
    pob: "Fort Belvoir, VA",
    securityClear: "TS/SCI",
    type: "CPFF",
  },
  {
    solicNumber: "HHS-NIH-NIDA-26-260",
    title: "Substance Use Disorder Treatment Research Data Analytics",
    agency: "Department of Health and Human Services",
    subAgency: "National Institute on Drug Abuse",
    description: "Data analytics support for SUD treatment research including large dataset analysis, statistical modeling, outcomes measurement, and dashboard development.",
    requirements: JSON.stringify(["Biostatistics expertise", "SAS/R/Python proficiency", "Health data governance", "NIH data use agreement compliance"]),
    naicsCode: "541511",
    setAside: "WOSB",
    valueMin: 3500000,
    valueMax: 6000000,
    dueDate: new Date("2026-05-25"),
    pob: "Bethesda, MD (Hybrid)",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "FA4861-26-R-A002",
    title: "Space Systems Ground Support Equipment Sustainment",
    agency: "Department of the Air Force",
    subAgency: "Space Systems Command",
    description: "Lifecycle sustainment, maintenance, and upgrade of ground support equipment for space launch and satellite operations at Cape Canaveral Space Force Station.",
    requirements: JSON.stringify(["Space launch experience", "GSE maintenance expertise", "Safety program management", "Clearance: Secret"]),
    naicsCode: "336419",
    setAside: "Unrestricted",
    valueMin: 55000000,
    valueMax: 90000000,
    dueDate: new Date("2026-07-15"),
    pob: "Cape Canaveral SFS, FL",
    securityClear: "Secret",
    type: "FFP",
  },
  {
    solicNumber: "W15QKN-26-R-0132",
    title: "Logistics & Supply Chain Management IT System",
    agency: "Department of the Army",
    subAgency: "Army Materiel Command",
    description: "Design, development, and O&M of a modern logistics information system supporting Army supply chain visibility from depot to point of need, integrating with SAP LMP.",
    requirements: JSON.stringify(["SAP logistics experience", "Army supply chain knowledge", "Agile software development", "FedRAMP High authorization"]),
    naicsCode: "541511",
    setAside: "SB",
    valueMin: 28000000,
    valueMax: 45000000,
    dueDate: new Date("2026-06-10"),
    pob: "Redstone Arsenal, AL",
    securityClear: "Secret",
    type: "FFP",
  },
  {
    solicNumber: "USCIS-26-R-00077",
    title: "Immigration Case Processing Support Services",
    agency: "Department of Homeland Security",
    subAgency: "USCIS",
    description: "Administrative and technical support for immigration case processing, including document scanning, data entry, case routing, customer service, and quality control at USCIS service centers.",
    requirements: JSON.stringify(["Document management experience", "High-volume data processing", "DHS suitability clearance", "PII handling compliance"]),
    naicsCode: "561110",
    setAside: "HUBZone",
    valueMin: 15000000,
    valueMax: 22000000,
    dueDate: new Date("2026-05-18"),
    pob: "Multiple USCIS Service Centers",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "DE-SC0026-R-001",
    title: "Nuclear Energy Advanced Reactor Safety Analysis",
    agency: "Department of Energy",
    subAgency: "Office of Nuclear Energy",
    description: "Technical safety analysis and regulatory support for advanced reactor designs including SMRs, molten salt, and fast spectrum reactors under NRC licensing.",
    requirements: JSON.stringify(["Nuclear engineering PhD", "NRC regulatory experience", "Thermal-hydraulic analysis", "RELAP/TRACE modeling"]),
    naicsCode: "541690",
    setAside: "Unrestricted",
    valueMin: 18000000,
    valueMax: 30000000,
    dueDate: new Date("2026-07-20"),
    pob: "Idaho Falls, ID / Remote",
    securityClear: "None",
    type: "CPFF",
  },
  {
    solicNumber: "VA119-26-R-0234",
    title: "Veterans Mental Health Telehealth Platform",
    agency: "Department of Veterans Affairs",
    subAgency: "Office of Connected Care",
    description: "Develop and operate a VA-integrated telehealth platform for mental health services delivery to veterans, including secure video, scheduling, EHR integration with VistA/Cerner.",
    requirements: JSON.stringify(["HIPAA/HITRUST compliance", "VistA/Cerner integration experience", "ADA accessibility compliance", "VA security assessment"]),
    naicsCode: "621111",
    setAside: "SDVOSB",
    valueMin: 25000000,
    valueMax: 40000000,
    dueDate: new Date("2026-06-05"),
    pob: "Nationwide (VA Medical Centers)",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "USMC-26-R-LOGEX-01",
    title: "Marine Corps Expeditionary Logistics Exercise Support",
    agency: "Department of the Navy",
    subAgency: "US Marine Corps",
    description: "Exercise planning, execution support, and after-action analysis for USMC expeditionary logistics exercises including BOLD ALLIGATOR and PACIFIC REACH events.",
    requirements: JSON.stringify(["USMC logistics background", "Exercise planning experience", "Secret clearance", "MCPP familiarity"]),
    naicsCode: "541990",
    setAside: "SB",
    valueMin: 4500000,
    valueMax: 8000000,
    dueDate: new Date("2026-05-22"),
    pob: "Camp Lejeune, NC / MARFORPAC",
    securityClear: "Secret",
    type: "T&M",
  },
  {
    solicNumber: "EPA-R5-26-R-00039",
    title: "Great Lakes Environmental Monitoring & Assessment",
    agency: "Environmental Protection Agency",
    subAgency: "Region 5 — Great Lakes National Program Office",
    description: "Environmental monitoring, sample collection, laboratory analysis, and data management for the Great Lakes Restoration Initiative across all five Great Lakes.",
    requirements: JSON.stringify(["Environmental science background", "Field sampling certification", "QAPP compliance", "GIS data management"]),
    naicsCode: "541620",
    setAside: "WOSB",
    valueMin: 6000000,
    valueMax: 10000000,
    dueDate: new Date("2026-06-18"),
    pob: "Chicago, IL / Field Sites",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "SOCOM-26-R-00181",
    title: "Special Operations Forces Training & Simulation",
    agency: "United States Special Operations Command",
    subAgency: null,
    description: "Design, develop, and deliver realistic training scenarios and simulation systems for SOF units including live-fire ranges, synthetic environments, and embedded training systems.",
    requirements: JSON.stringify(["SOF background preferred", "Training system development", "TS/SCI clearance", "Orlando-area presence preferred"]),
    naicsCode: "611699",
    setAside: "Unrestricted",
    valueMin: 95000000,
    valueMax: 150000000,
    dueDate: new Date("2026-07-30"),
    pob: "MacDill AFB, FL",
    securityClear: "TS/SCI",
    type: "IDIQ",
  },
  {
    solicNumber: "FEMA-26-R-HMGP-004",
    title: "Hazard Mitigation Grant Program Technical Assistance",
    agency: "Department of Homeland Security",
    subAgency: "FEMA",
    description: "Technical assistance to states and local jurisdictions applying for and implementing FEMA HMGP grants, including project development, benefit-cost analysis, environmental review, and closeout.",
    requirements: JSON.stringify(["FEMA HMGP experience", "BCA software proficiency", "Grant management background", "Environmental compliance"]),
    naicsCode: "541611",
    setAside: "8(a)",
    valueMin: 7000000,
    valueMax: 12000000,
    dueDate: new Date("2026-05-28"),
    pob: "Washington, DC / Field Offices",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "NSF-26-R-00056",
    title: "Antarctic Research Station Logistics Support",
    agency: "National Science Foundation",
    subAgency: "Office of Polar Programs",
    description: "Full logistics support for US Antarctic Program operations at McMurdo Station, South Pole Station, and Palmer Station including transportation, facilities, science support, and life support.",
    requirements: JSON.stringify(["Extreme environment logistics", "Polar operations experience", "HACCP food safety", "Medical support capability"]),
    naicsCode: "488999",
    setAside: "Unrestricted",
    valueMin: 200000000,
    valueMax: 350000000,
    dueDate: new Date("2026-09-01"),
    pob: "Antarctica (McMurdo/South Pole/Palmer)",
    securityClear: "None",
    type: "CPFF",
  },
  {
    solicNumber: "TREAS-IRS-26-R-0099",
    title: "IRS Tax Processing Modernization — Submission Processing",
    agency: "Department of the Treasury",
    subAgency: "Internal Revenue Service",
    description: "Modernize IRS paper return processing through automation, digitization, and workflow management to eliminate backlog and meet processing timelines.",
    requirements: JSON.stringify(["IRS processing experience", "OCR/ICR technology", "SAFe Agile", "Sensitive but unclassified data handling"]),
    naicsCode: "541512",
    setAside: "Unrestricted",
    valueMin: 60000000,
    valueMax: 100000000,
    dueDate: new Date("2026-07-10"),
    pob: "Multiple IRS Campuses",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "HQ0147-26-R-0021",
    title: "Joint AI Center (JAIC) Data Labeling & Annotation",
    agency: "Department of Defense",
    subAgency: "Chief Digital & AI Office (CDAO)",
    description: "Large-scale data labeling, annotation, and curation services to support DoD AI/ML model training across imagery, text, sensor data, and multi-modal datasets.",
    requirements: JSON.stringify(["Data annotation at scale", "ML/AI pipeline experience", "Data governance framework", "Secret clearance preferred"]),
    naicsCode: "541511",
    setAside: "SB",
    valueMin: 30000000,
    valueMax: 50000000,
    dueDate: new Date("2026-06-22"),
    pob: "Washington, DC (Hybrid)",
    securityClear: "Secret",
    type: "T&M",
  },
  {
    solicNumber: "CBP-26-R-BWT-003",
    title: "Border Wall Technology Integration & O&M",
    agency: "Department of Homeland Security",
    subAgency: "Customs and Border Protection",
    description: "Integration, operations, and maintenance of CBP border technology including sensors, cameras, radar systems, and communication networks along the southern border.",
    requirements: JSON.stringify(["Border security technology", "Remote operations experience", "Secret clearance", "Southwest border familiarity"]),
    naicsCode: "561612",
    setAside: "Unrestricted",
    valueMin: 110000000,
    valueMax: 175000000,
    dueDate: new Date("2026-08-15"),
    pob: "Southwest Border (TX/NM/AZ/CA)",
    securityClear: "Secret",
    type: "FFP",
  },
  {
    solicNumber: "DOS-26-R-DIPLO-007",
    title: "Overseas Embassy Security Assessment Services",
    agency: "Department of State",
    subAgency: "Bureau of Diplomatic Security",
    description: "Physical security assessments, threat analysis, and security system design for US diplomatic facilities overseas including embassies, consulates, and American Presence Posts.",
    requirements: JSON.stringify(["Diplomatic security background", "Overseas assessment experience", "TS/SCI clearance", "Physical security expertise"]),
    naicsCode: "561621",
    setAside: "SDVOSB",
    valueMin: 18000000,
    valueMax: 28000000,
    dueDate: new Date("2026-06-30"),
    pob: "Arlington, VA / Overseas TDY",
    securityClear: "TS/SCI",
    type: "T&M",
  },
  {
    solicNumber: "USACE-LRN-26-R-00112",
    title: "Ohio River Navigation Infrastructure Maintenance",
    agency: "Department of the Army",
    subAgency: "Army Corps of Engineers — Louisville District",
    description: "Maintenance dredging, lock & dam repair, and navigation infrastructure maintenance for the Ohio River from Pittsburgh, PA to Cairo, IL.",
    requirements: JSON.stringify(["Dredging operations", "Lock & dam maintenance", "USACE EM385-1-1 compliance", "Maritime safety certification"]),
    naicsCode: "237990",
    setAside: "Unrestricted",
    valueMin: 40000000,
    valueMax: 65000000,
    dueDate: new Date("2026-07-25"),
    pob: "Ohio River (Pittsburgh, PA to Cairo, IL)",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "AHRQ-26-R-0031",
    title: "Healthcare Quality Measurement & Reporting System",
    agency: "Department of Health and Human Services",
    subAgency: "Agency for Healthcare Research and Quality",
    description: "Develop and maintain AHRQ's National Healthcare Quality and Disparities reporting systems, databases, and public-facing tools used by policymakers and researchers.",
    requirements: JSON.stringify(["Health IT development", "SAS/SQL expertise", "Section 508 compliance", "Public health data experience"]),
    naicsCode: "541511",
    setAside: "WOSB",
    valueMin: 9000000,
    valueMax: 15000000,
    dueDate: new Date("2026-05-30"),
    pob: "Rockville, MD (Hybrid)",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "MDA-26-R-00088",
    title: "Missile Defense Interceptor Flight Test Support",
    agency: "Missile Defense Agency",
    subAgency: null,
    description: "Engineering and technical support for MDA ground-based and sea-based interceptor flight test events including test planning, range safety, telemetry, and post-flight analysis.",
    requirements: JSON.stringify(["Flight test experience", "Range safety background", "TS/SCI clearance", "Missile systems knowledge"]),
    naicsCode: "541330",
    setAside: "Unrestricted",
    valueMin: 70000000,
    valueMax: 110000000,
    dueDate: new Date("2026-08-10"),
    pob: "Schriever SFB, CO / Kwajalein Atoll",
    securityClear: "TS/SCI",
    type: "CPFF",
  },
  {
    solicNumber: "DOT-FAA-26-R-00231",
    title: "NextGen Air Traffic Control Software Sustainment",
    agency: "Department of Transportation",
    subAgency: "Federal Aviation Administration",
    description: "Software development, maintenance, and sustainment of FAA NextGen air traffic management systems including ERAM, STARS, and TBFM at en route centers and TRACONs.",
    requirements: JSON.stringify(["ATC software experience", "Ada/Java development", "FAA software standards", "24/7 support capability"]),
    naicsCode: "541511",
    setAside: "Unrestricted",
    valueMin: 45000000,
    valueMax: 75000000,
    dueDate: new Date("2026-07-08"),
    pob: "Washington, DC / En Route Centers",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "USDA-NRCS-26-R-00044",
    title: "Conservation Program Technical Assistance — Midwest",
    agency: "Department of Agriculture",
    subAgency: "Natural Resources Conservation Service",
    description: "Technical assistance to farmers implementing conservation practices under USDA EQIP and CSP programs in Iowa, Illinois, Indiana, Ohio, and Michigan.",
    requirements: JSON.stringify(["NRCS standards knowledge", "Agronomy background", "Conservation planning", "Agricultural background"]),
    naicsCode: "541620",
    setAside: "SDVOSB",
    valueMin: 5500000,
    valueMax: 9000000,
    dueDate: new Date("2026-05-29"),
    pob: "Midwest States (IA/IL/IN/OH/MI)",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "USCG-26-R-00067",
    title: "Coast Guard Cutter Maintenance & Repair IDIQ",
    agency: "Department of Homeland Security",
    subAgency: "US Coast Guard",
    description: "Vessel maintenance, dry-docking, and repair services for USCG National Security Cutters and Fast Response Cutters under an IDIQ multiple-award contract.",
    requirements: JSON.stringify(["Ship repair yard capabilities", "USCG vessel experience", "NAVSEA 0900 standards", "Qualified workforce"]),
    naicsCode: "336611",
    setAside: "SB",
    valueMin: 0,
    valueMax: 250000000,
    dueDate: new Date("2026-08-20"),
    pob: "Various US Ports",
    securityClear: "None",
    type: "IDIQ",
  },
  {
    solicNumber: "NGA-26-R-GEOINT-02",
    title: "GEOINT Analysis & Production Support",
    agency: "National Geospatial-Intelligence Agency",
    subAgency: null,
    description: "Geospatial intelligence analysis, image exploitation, and production support for NGA's global GEOINT mission including change detection, 3D modeling, and foundation data maintenance.",
    requirements: JSON.stringify(["TS/SCI with CI Poly", "GEOINT analysis experience", "SOCET GXP/ArcGIS proficiency", "Multi-INT fusion"]),
    naicsCode: "541370",
    setAside: "Unrestricted",
    valueMin: 80000000,
    valueMax: 130000000,
    dueDate: new Date("2026-09-15"),
    pob: "Springfield, VA",
    securityClear: "TS/SCI",
    type: "CPFF",
  },
  {
    solicNumber: "BOP-26-R-00023",
    title: "Federal Prison Healthcare Services — Northeast Region",
    agency: "Department of Justice",
    subAgency: "Bureau of Prisons",
    description: "Comprehensive healthcare services at federal correctional institutions in the Northeast including primary care, mental health, dental, and pharmacy services.",
    requirements: JSON.stringify(["Correctional healthcare experience", "BOP compliance requirements", "JCAHO accreditation preferred", "DEA registration"]),
    naicsCode: "621111",
    setAside: "Unrestricted",
    valueMin: 35000000,
    valueMax: 55000000,
    dueDate: new Date("2026-06-25"),
    pob: "Northeast Federal Prisons",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "LOC-26-R-00015",
    title: "Library of Congress Digital Preservation & Curation",
    agency: "Library of Congress",
    subAgency: null,
    description: "Digital preservation services for the Library of Congress national digital collections including format migration, metadata enrichment, quality assurance, and long-term storage management.",
    requirements: JSON.stringify(["Digital preservation standards", "Library/archival science", "BagIt/OAIS compliance", "Audio-visual digitization"]),
    naicsCode: "519120",
    setAside: "8(a)",
    valueMin: 4000000,
    valueMax: 7000000,
    dueDate: new Date("2026-05-27"),
    pob: "Washington, DC",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "DHS-TSA-26-R-00134",
    title: "Airport Checkpoint Technology Deployment & Training",
    agency: "Department of Homeland Security",
    subAgency: "Transportation Security Administration",
    description: "Nationwide deployment, maintenance, and TSO training for next-generation checkpoint screening equipment including CT scanners, AIT, and ETD systems.",
    requirements: JSON.stringify(["TSA equipment experience", "Nationwide deployment capability", "Training program development", "140+ airport presence"]),
    naicsCode: "238210",
    setAside: "Unrestricted",
    valueMin: 125000000,
    valueMax: 200000000,
    dueDate: new Date("2026-08-28"),
    pob: "Nationwide Airports",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "USAF-AETC-26-R-00078",
    title: "Undergraduate Pilot Training (UPT) Contractor Support",
    agency: "Department of the Air Force",
    subAgency: "Air Education & Training Command",
    description: "Contractor-provided academic instruction, simulator operation, and administrative support for Air Force Undergraduate Pilot Training at Vance, Columbus, and Laughlin AFBs.",
    requirements: JSON.stringify(["Military pilot qualification", "FAA ATP certificate", "T-6/T-38 currency preferred", "SECRET clearance"]),
    naicsCode: "611512",
    setAside: "Unrestricted",
    valueMin: 90000000,
    valueMax: 140000000,
    dueDate: new Date("2026-07-18"),
    pob: "Vance AFB OK / Columbus AFB MS / Laughlin AFB TX",
    securityClear: "Secret",
    type: "FFP",
  },
  {
    solicNumber: "CDC-NCEZID-26-R-004",
    title: "Zoonotic Disease Surveillance & Response Support",
    agency: "Department of Health and Human Services",
    subAgency: "CDC National Center for Emerging & Zoonotic Infectious Diseases",
    description: "Laboratory and epidemiological support for zoonotic disease surveillance programs including rabies, hantavirus, plague, and emerging infectious disease outbreak investigations.",
    requirements: JSON.stringify(["Zoonotic disease expertise", "BSL-3 lab experience", "One Health framework", "Outbreak response"]),
    naicsCode: "621511",
    setAside: "WOSB",
    valueMin: 6500000,
    valueMax: 11000000,
    dueDate: new Date("2026-06-12"),
    pob: "Atlanta, GA / Field Response",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "DLA-26-R-FUEL-009",
    title: "Defense Fuel Support Point — Korea Theater",
    agency: "Defense Logistics Agency",
    subAgency: "DLA Energy",
    description: "Bulk petroleum storage, distribution, and quality surveillance at US military fuel support points throughout the Republic of Korea.",
    requirements: JSON.stringify(["Bulk petroleum operations", "Korea theater experience", "SOFA compliance", "Environmental compliance"]),
    naicsCode: "447190",
    setAside: "Unrestricted",
    valueMin: 15000000,
    valueMax: 25000000,
    dueDate: new Date("2026-06-28"),
    pob: "Republic of Korea",
    securityClear: "Secret",
    type: "FFP",
  },
  {
    solicNumber: "USAID-AFR-26-R-00201",
    title: "Sub-Saharan Africa Food Security Program Implementation",
    agency: "US Agency for International Development",
    subAgency: "Bureau for Humanitarian Assistance",
    description: "Implement food security interventions in East and West Africa including emergency food assistance, agriculture development, nutrition programs, and resilience building.",
    requirements: JSON.stringify(["USAID experience", "Food security expertise", "Africa regional presence", "Title II regulations"]),
    naicsCode: "923120",
    setAside: "Unrestricted",
    valueMin: 50000000,
    valueMax: 80000000,
    dueDate: new Date("2026-08-05"),
    pob: "Sub-Saharan Africa (Multiple Countries)",
    securityClear: "None",
    type: "CPFF",
  },
  {
    solicNumber: "SSA-26-R-ITMOD-012",
    title: "Social Security Administration IT Modernization",
    agency: "Social Security Administration",
    subAgency: null,
    description: "Agile software development and system modernization for SSA's core benefits processing systems, transitioning legacy COBOL mainframe to modern cloud-native architecture.",
    requirements: JSON.stringify(["COBOL modernization experience", "SSA domain knowledge preferred", "SAFe Agile certification", "FedRAMP High"]),
    naicsCode: "541512",
    setAside: "Unrestricted",
    valueMin: 75000000,
    valueMax: 120000000,
    dueDate: new Date("2026-07-22"),
    pob: "Baltimore, MD (Hybrid)",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "BLM-26-R-WILD-006",
    title: "Wildfire Fuels Reduction & Forest Health Services",
    agency: "Department of the Interior",
    subAgency: "Bureau of Land Management",
    description: "Mechanical and prescribed fire treatments to reduce wildfire fuel loads and improve forest health on BLM-administered lands in California, Oregon, and Washington.",
    requirements: JSON.stringify(["NWCG certified crews", "Prescribed fire qualifications", "Environmental compliance", "NEPA documentation"]),
    naicsCode: "115310",
    setAside: "SB",
    valueMin: 8000000,
    valueMax: 14000000,
    dueDate: new Date("2026-05-31"),
    pob: "BLM Western States",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "DARPA-TTO-26-R-00034",
    title: "Autonomous Systems for Contested Logistics",
    agency: "Defense Advanced Research Projects Agency",
    subAgency: "Tactical Technology Office",
    description: "Research and prototype development of autonomous ground and air vehicles for logistics resupply in GPS-denied, contested environments at tactical echelons.",
    requirements: JSON.stringify(["Autonomous systems R&D", "GNSS-denied navigation", "ML/AI for autonomy", "TS/SCI preferred"]),
    naicsCode: "541715",
    setAside: "Unrestricted",
    valueMin: 12000000,
    valueMax: 20000000,
    dueDate: new Date("2026-06-20"),
    pob: "Arlington, VA / Test Sites",
    securityClear: "Secret",
    type: "CPFF",
  },
  {
    solicNumber: "NRC-26-R-00067",
    title: "Nuclear Regulatory Commission Inspection Support",
    agency: "Nuclear Regulatory Commission",
    subAgency: null,
    description: "Technical support for NRC reactor safety inspections, license renewal reviews, and security assessments at operating commercial nuclear power plants.",
    requirements: JSON.stringify(["Licensed reactor operator preferred", "10 CFR compliance", "NRC inspection experience", "Reactor physics background"]),
    naicsCode: "541690",
    setAside: "SDVOSB",
    valueMin: 11000000,
    valueMax: 18000000,
    dueDate: new Date("2026-06-16"),
    pob: "Rockville, MD / Plant Sites Nationwide",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "AF-AFWERX-26-R-001",
    title: "AFWERX Innovation Accelerator Program Support",
    agency: "Department of the Air Force",
    subAgency: "AFWERX",
    description: "Program management, partnership brokering, and innovation acceleration services for AFWERX programs including Spark, Agility Prime, and the AFWERX Flagship program.",
    requirements: JSON.stringify(["Innovation program experience", "Startup/VC ecosystem knowledge", "DAF partnership development", "Secret clearance preferred"]),
    naicsCode: "541611",
    setAside: "8(a)",
    valueMin: 8000000,
    valueMax: 13000000,
    dueDate: new Date("2026-05-24"),
    pob: "Austin, TX / Remote",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "TRANSCOM-26-R-00019",
    title: "Strategic Air Mobility Planning & Analysis",
    agency: "United States Transportation Command",
    subAgency: null,
    description: "Operations research, modeling and simulation, and analytical support for USTRANSCOM airlift planning, optimization, and readiness assessment.",
    requirements: JSON.stringify(["OR/SA background", "Airlift modeling experience", "TS/SCI clearance", "JDPAT or GDSSIM proficiency"]),
    naicsCode: "541690",
    setAside: "Unrestricted",
    valueMin: 22000000,
    valueMax: 35000000,
    dueDate: new Date("2026-07-05"),
    pob: "Scott AFB, IL",
    securityClear: "TS/SCI",
    type: "CPFF",
  },
  {
    solicNumber: "HUD-26-R-FAIR-003",
    title: "Fair Housing Enforcement & Investigations Support",
    agency: "Department of Housing and Urban Development",
    subAgency: "Office of Fair Housing and Equal Opportunity",
    description: "Legal, investigative, and analytical support for HUD fair housing complaint processing, systemic investigations, and compliance monitoring under the Fair Housing Act.",
    requirements: JSON.stringify(["Fair housing law expertise", "Civil rights investigation", "Legal research capability", "HUD FHEO experience"]),
    naicsCode: "541110",
    setAside: "WOSB",
    valueMin: 5000000,
    valueMax: 8500000,
    dueDate: new Date("2026-05-26"),
    pob: "Washington, DC (Hybrid)",
    securityClear: "None",
    type: "T&M",
  },
  {
    solicNumber: "AFRICOM-26-R-00055",
    title: "Africa Security Cooperation Program Support",
    agency: "Department of Defense",
    subAgency: "US Africa Command",
    description: "Planning, execution, and assessment support for Security Cooperation programs across Sub-Saharan Africa including combined training events, IMET, FMF management, and mil-to-mil engagements.",
    requirements: JSON.stringify(["AFRICOM experience", "FMS/FMF knowledge", "African language proficiency preferred", "TS/SCI clearance"]),
    naicsCode: "541990",
    setAside: "SDVOSB",
    valueMin: 16000000,
    valueMax: 26000000,
    dueDate: new Date("2026-06-14"),
    pob: "Stuttgart, Germany / OCONUS Africa TDY",
    securityClear: "TS/SCI",
    type: "T&M",
  },
  {
    solicNumber: "FWS-26-R-HABITAT-001",
    title: "Endangered Species Habitat Restoration — Florida",
    agency: "Department of the Interior",
    subAgency: "US Fish and Wildlife Service",
    description: "Ecological restoration of critical habitat for Florida scrub-jay, Florida panther, and gopher tortoise on National Wildlife Refuges and partner lands in central Florida.",
    requirements: JSON.stringify(["Florida ecology expertise", "Prescribed fire certification", "ESA Section 7 compliance", "Invasive species management"]),
    naicsCode: "541620",
    setAside: "SB",
    valueMin: 3000000,
    valueMax: 5500000,
    dueDate: new Date("2026-05-23"),
    pob: "Central Florida National Wildlife Refuges",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "STRATCOM-26-R-NC3-02",
    title: "Nuclear Command, Control & Communications (NC3) Modernization",
    agency: "United States Strategic Command",
    subAgency: null,
    description: "Engineering, architecture, and integration support for modernizing the Nuclear Command, Control, and Communications enterprise ensuring nuclear deterrence mission assurance.",
    requirements: JSON.stringify(["NC3 systems background", "STRATCOM mission familiarity", "TS/SCI with Full Scope Poly", "Nuclear systems engineering"]),
    naicsCode: "541330",
    setAside: "Unrestricted",
    valueMin: 150000000,
    valueMax: 250000000,
    dueDate: new Date("2026-09-20"),
    pob: "Offutt AFB, NE",
    securityClear: "TS/SCI",
    type: "IDIQ",
  },
  {
    solicNumber: "FEMA-26-R-IPAWS-001",
    title: "IPAWS Alert & Warning System Operations & Maintenance",
    agency: "Department of Homeland Security",
    subAgency: "FEMA Integrated Public Alert & Warning System",
    description: "Operations, maintenance, and enhancement of the IPAWS national alert and warning infrastructure including WEA, EAS, and NOAA Weather Radio system integration.",
    requirements: JSON.stringify(["Alert & warning systems", "AWS GovCloud experience", "24/7 NOC operations", "IPAWS COG management"]),
    naicsCode: "517919",
    setAside: "HUBZone",
    valueMin: 12000000,
    valueMax: 20000000,
    dueDate: new Date("2026-06-08"),
    pob: "Washington, DC",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "NASA-GSFC-26-R-00188",
    title: "Earth Science Mission Operations & Data Processing",
    agency: "National Aeronautics & Space Administration",
    subAgency: "Goddard Space Flight Center",
    description: "Spacecraft operations, science data processing, and archiving support for NASA Earth science missions including Terra, Aqua, and future climate monitoring satellites.",
    requirements: JSON.stringify(["Spacecraft operations experience", "Science data processing", "EOSDIS architecture", "Mission operations background"]),
    naicsCode: "541712",
    setAside: "Unrestricted",
    valueMin: 65000000,
    valueMax: 100000000,
    dueDate: new Date("2026-07-28"),
    pob: "Greenbelt, MD",
    securityClear: "None",
    type: "CPFF",
  },
  {
    solicNumber: "DHS-CISA-26-R-00041",
    title: "Critical Infrastructure Cyber Defense Services",
    agency: "Department of Homeland Security",
    subAgency: "Cybersecurity & Infrastructure Security Agency",
    description: "Cybersecurity advisory services, threat hunting, vulnerability assessments, and incident response support for critical infrastructure sectors nationwide under CISA's protective programs.",
    requirements: JSON.stringify(["ICS/OT cybersecurity", "CISA sector experience", "CISSP/CISM certification", "Critical infrastructure expertise"]),
    naicsCode: "541512",
    setAside: "Unrestricted",
    valueMin: 55000000,
    valueMax: 90000000,
    dueDate: new Date("2026-07-12"),
    pob: "Arlington, VA / Field (Nationwide)",
    securityClear: "Secret",
    type: "T&M",
  },
  {
    solicNumber: "INDO-PAC-26-R-00099",
    title: "Indo-Pacific Theater Campaign Support Services",
    agency: "Department of Defense",
    subAgency: "US Indo-Pacific Command",
    description: "Operational planning, exercises support, partner nation engagement, and campaign analysis support for USINDOPACOM theater campaign objectives across the Indo-Pacific.",
    requirements: JSON.stringify(["INDOPACOM experience", "Operational planning background", "TS/SCI clearance", "Asia-Pacific regional expertise"]),
    naicsCode: "541990",
    setAside: "Unrestricted",
    valueMin: 35000000,
    valueMax: 60000000,
    dueDate: new Date("2026-07-02"),
    pob: "Camp H.M. Smith, HI",
    securityClear: "TS/SCI",
    type: "T&M",
  },
  {
    solicNumber: "ABMC-26-R-MAINTAIN-001",
    title: "American Battle Monuments Commission Cemetery Maintenance",
    agency: "American Battle Monuments Commission",
    subAgency: null,
    description: "Grounds maintenance, monument restoration, visitor services, and facility management at ABMC overseas cemeteries and memorials in France, Belgium, Luxembourg, and Italy.",
    requirements: JSON.stringify(["Historic preservation experience", "Overseas operations capability", "Grounds maintenance expertise", "Veteran family liaison"]),
    naicsCode: "812220",
    setAside: "Unrestricted",
    valueMin: 20000000,
    valueMax: 32000000,
    dueDate: new Date("2026-06-22"),
    pob: "Western Europe (France/Belgium/Luxembourg/Italy)",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "APHIS-26-R-PPQ-007",
    title: "Plant Protection & Quarantine Inspection Services",
    agency: "Department of Agriculture",
    subAgency: "Animal and Plant Health Inspection Service",
    description: "Agricultural inspection services at ports of entry to prevent introduction of invasive pests and diseases, including inspection of passengers, cargo, and mail.",
    requirements: JSON.stringify(["Agricultural inspection background", "CBP port experience", "Entomology/plant pathology", "Spanish language preferred"]),
    naicsCode: "541620",
    setAside: "8(a)",
    valueMin: 7500000,
    valueMax: 12000000,
    dueDate: new Date("2026-05-21"),
    pob: "Ports of Entry (Nationwide)",
    securityClear: "None",
    type: "FFP",
  },
  {
    solicNumber: "DISA-26-R-JWICS-003",
    title: "JWICS Network Operations & Transport Services",
    agency: "Defense Information Systems Agency",
    subAgency: null,
    description: "Operations, maintenance, and lifecycle management of the Joint Worldwide Intelligence Communications System (JWICS) global network transport and associated switching infrastructure.",
    requirements: JSON.stringify(["TS/SCI with CI Poly", "JWICS operations background", "SATCOM/fiber transport", "DISA mission familiarity"]),
    naicsCode: "517311",
    setAside: "Unrestricted",
    valueMin: 120000000,
    valueMax: 190000000,
    dueDate: new Date("2026-08-25"),
    pob: "Fort Meade, MD / CONUS/OCONUS Sites",
    securityClear: "TS/SCI",
    type: "FFP",
  },
];

async function main() {
  console.log("🌱 Seeding Zam.guv database...");

  // Create admin user
  const adminHash = await bcrypt.hash("Admin@2026!", 10);
  await prisma.user.upsert({
    where: { email: "admin@zam.guv" },
    update: {},
    create: {
      email: "admin@zam.guv",
      name: "System Administrator",
      role: "admin",
      passwordHash: adminHash,
    },
  });

  // Create VP users
  const vpPassHash = await bcrypt.hash("VP@Secure2026!", 10);
  const vps = [
    { email: "sarah.chen@company.gov", name: "Sarah Chen" },
    { email: "james.walker@company.gov", name: "James Walker" },
    { email: "priya.patel@company.gov", name: "Priya Patel" },
    { email: "marcus.johnson@company.gov", name: "Marcus Johnson" },
    { email: "elena.rodriguez@company.gov", name: "Elena Rodriguez" },
  ];

  for (const vp of vps) {
    await prisma.user.upsert({
      where: { email: vp.email },
      update: {},
      create: {
        ...vp,
        role: "vp",
        passwordHash: vpPassHash,
      },
    });
  }

  // Seed contracts
  for (const contract of contracts) {
    await prisma.contract.upsert({
      where: { solicNumber: contract.solicNumber },
      update: {},
      create: {
        ...contract,
        postedDate: new Date(),
      },
    });
  }

  const contractCount = await prisma.contract.count();
  const userCount = await prisma.user.count();
  console.log(`✅ Seeded ${contractCount} contracts and ${userCount} users`);
  console.log("\n📋 Login credentials:");
  console.log("  Admin: admin@zam.guv / Admin@2026!");
  console.log("  VP:    sarah.chen@company.gov / VP@Secure2026!");
  console.log("         james.walker@company.gov / VP@Secure2026!");
  console.log("         (and 3 more VPs, same password)");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
