import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as any);

const idiqContracts = [
  {
    solicNumber: "W912DR-26-T-0001",
    title: "Army Installation IT Infrastructure Task Order — Fort Bragg",
    agency: "Department of the Army",
    subAgency: "Army Corps of Engineers",
    description: "Task order under the ITES-3S IDIQ for full-stack IT infrastructure modernization at Fort Bragg including network upgrades, server virtualization, and end-user computing refresh. Contractor shall deliver within a 24-month performance period with options for two additional years.",
    requirements: JSON.stringify(["ITES-3S contract holder", "DoD network engineering certification", "Secret clearance for all personnel", "DISA STIG compliance"]),
    naicsCode: "541512",
    setAside: "Unrestricted",
    valueMin: 18000000,
    valueMax: 32000000,
    dueDate: new Date("2026-06-15"),
    pob: "Fort Bragg, NC",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0002",
    title: "Cyber Operations Center Staffing — Army Reserve",
    agency: "Department of the Army",
    subAgency: "Army Reserve Command",
    description: "Task order for cybersecurity operations staff augmentation at Army Reserve cyber units under the ITES-3H IDIQ vehicle. Personnel shall provide 24/7 SOC monitoring, incident response, and vulnerability management across Reserve Component networks.",
    requirements: JSON.stringify(["Active TS/SCI clearance", "DoD 8570.01-M IAT Level III", "SIEM platform expertise (Splunk/QRadar)", "Army Reserve familiarity"]),
    naicsCode: "541519",
    setAside: "SB",
    valueMin: 8000000,
    valueMax: 15000000,
    dueDate: new Date("2026-07-01"),
    pob: "Fort McCoy, WI",
    securityClear: "TS/SCI",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0001",
    title: "Aviation Platform Software Sustainment — Apache/Black Hawk",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Aviation",
    description: "Software maintenance and upgrade task order for Army rotary-wing platforms under the AMCOM Software Support Activity IDIQ. Scope includes embedded mission software, avionics integration, and software safety analysis for AH-64E and UH-60M fleets.",
    requirements: JSON.stringify(["DO-178C Level A/B experience", "Avionics software integration", "Army aviation platform knowledge", "SECRET clearance minimum"]),
    naicsCode: "336413",
    setAside: "Unrestricted",
    valueMin: 25000000,
    valueMax: 45000000,
    dueDate: new Date("2026-08-01"),
    pob: "Redstone Arsenal, AL",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0002",
    title: "Logistics Modernization Program SAP ERP Task Order",
    agency: "Department of the Army",
    subAgency: "Army Materiel Command",
    description: "SAP-based logistics ERP sustainment and enhancement task order covering financial management, supply chain, plant maintenance, and production planning modules. Work supports Army LMP operations at depots and arsenals nationwide.",
    requirements: JSON.stringify(["SAP ECC/S4HANA expertise", "Federal financial compliance (FAR/DFARS)", "Army depot operations knowledge", "Secret clearance for some tasks"]),
    naicsCode: "541511",
    setAside: "SB",
    valueMin: 12000000,
    valueMax: 22000000,
    dueDate: new Date("2026-06-20"),
    pob: "Rock Island Arsenal, IL",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0003",
    title: "Geospatial Engineering Services — USACE Nationwide",
    agency: "Department of the Army",
    subAgency: "US Army Corps of Engineers",
    description: "Task order for geospatial data collection, processing, and analysis services supporting USACE civil works and military construction projects nationwide. Deliverables include LiDAR surveys, hydrographic surveys, and GIS database development.",
    requirements: JSON.stringify(["Licensed Professional Surveyor", "LiDAR/hydrographic survey capability", "USACE EM 1110-1-1005 compliance", "Esri GIS certification"]),
    naicsCode: "541370",
    setAside: "SDVOSB",
    valueMin: 5000000,
    valueMax: 9000000,
    dueDate: new Date("2026-07-15"),
    pob: "Multiple USACE Districts",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0004",
    title: "Facilities Engineering O&M — Fort Cavazos Installation",
    agency: "Department of the Army",
    subAgency: "Installation Management Command",
    description: "Operations and maintenance task order for Fort Cavazos facilities including HVAC, electrical, plumbing, and grounds maintenance under the LOGCAP V IDIQ. Performance covers 1,400+ facilities across the 218,000-acre installation.",
    requirements: JSON.stringify(["LOGCAP V contract holder", "Installation facilities management", "Army IMCOM standards compliance", "Qualified trades workforce"]),
    naicsCode: "561210",
    setAside: "Unrestricted",
    valueMin: 40000000,
    valueMax: 65000000,
    dueDate: new Date("2026-09-01"),
    pob: "Fort Cavazos, TX",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0003",
    title: "Counter-UAS Electronic Warfare System Integration",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Missiles & Space",
    description: "Systems engineering and integration task order for Army counter-unmanned aerial systems electronic warfare capabilities under the MFCS IDIQ. Work includes sensor fusion, command-and-control software, and field test support at Yuma Proving Ground.",
    requirements: JSON.stringify(["EW systems integration", "Counter-UAS domain expertise", "TS/SCI clearance", "RF engineering background"]),
    naicsCode: "541330",
    setAside: "Unrestricted",
    valueMin: 30000000,
    valueMax: 55000000,
    dueDate: new Date("2026-08-15"),
    pob: "Yuma Proving Ground, AZ / Redstone Arsenal, AL",
    securityClear: "TS/SCI",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0005",
    title: "Medical Simulation Training Systems — Army MEDCOM",
    agency: "Department of the Army",
    subAgency: "Army Medical Command",
    description: "Task order for procurement, installation, and sustainment of medical simulation training systems at Army medical treatment facilities under the MEDMARC IDIQ. Systems include patient simulators, surgical trainers, and mass casualty simulation suites.",
    requirements: JSON.stringify(["Medical simulation expertise", "FDA device compliance", "MEDMARC contract holder", "Army MTF integration"]),
    naicsCode: "339113",
    setAside: "WOSB",
    valueMin: 6000000,
    valueMax: 11000000,
    dueDate: new Date("2026-07-10"),
    pob: "Multiple Army MTFs (CONUS)",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0004",
    title: "Rotary Wing Depot Maintenance — Corpus Christi Army Depot",
    agency: "Department of the Army",
    subAgency: "Corpus Christi Army Depot",
    description: "Depot-level maintenance and overhaul task order for Army helicopters at CCAD covering engine, transmission, and airframe overhaul for CH-47F Chinook and OH-58D Kiowa platforms under the AMCOM LSSI IDIQ.",
    requirements: JSON.stringify(["FAA Repair Station Certificate", "Army depot maintenance experience", "Helicopter overhaul capability", "DCMA quality oversight"]),
    naicsCode: "488190",
    setAside: "Unrestricted",
    valueMin: 50000000,
    valueMax: 80000000,
    dueDate: new Date("2026-09-15"),
    pob: "Corpus Christi Army Depot, TX",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0006",
    title: "Environmental Remediation — Aberdeen Proving Ground",
    agency: "Department of the Army",
    subAgency: "Army Corps of Engineers — Baltimore District",
    description: "Remedial action task order for legacy chemical agent and industrial waste remediation at Aberdeen Proving Ground under the HTRW IDIQ. Work includes excavation, soil treatment, groundwater extraction, and long-term monitoring.",
    requirements: JSON.stringify(["CERCLA remediation experience", "Chemical agent safety qualifications", "Maryland MDE certification", "USACE HTRW qualification"]),
    naicsCode: "562211",
    setAside: "Unrestricted",
    valueMin: 35000000,
    valueMax: 60000000,
    dueDate: new Date("2026-08-20"),
    pob: "Aberdeen Proving Ground, MD",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0005",
    title: "Ground Combat Vehicle Survivability Enhancement",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Ground Combat Systems",
    description: "Engineering and integration task order for survivability enhancements to M1A2 SEPv3 Abrams and M2A4 Bradley platforms including reactive armor, active protection systems, and electronic countermeasures under the TARDEC IDIQ.",
    requirements: JSON.stringify(["Ground vehicle survivability experience", "Armor/APS integration", "Live-fire test support", "TS/SCI clearance for some CDRLs"]),
    naicsCode: "336992",
    setAside: "Unrestricted",
    valueMin: 60000000,
    valueMax: 95000000,
    dueDate: new Date("2026-07-25"),
    pob: "Warren, MI / Aberdeen Proving Ground, MD",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0007",
    title: "Construction Quality Management — MILCON Projects",
    agency: "Department of the Army",
    subAgency: "Army Corps of Engineers — Savannah District",
    description: "Construction quality management and inspection services task order for military construction projects at Fort Stewart and Hunter Army Airfield under the AE IDIQ. Scope covers barracks, motor pools, and hangar construction.",
    requirements: JSON.stringify(["USACE construction inspection", "AE IDIQ contract holder", "CQM-C certification", "MILCON project experience"]),
    naicsCode: "541310",
    setAside: "8(a)",
    valueMin: 4000000,
    valueMax: 8000000,
    dueDate: new Date("2026-06-30"),
    pob: "Fort Stewart / Hunter AAF, GA",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0006",
    title: "Integrated Air & Missile Defense Battle Command Software",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Missiles & Space",
    description: "Software development and integration task order for IAMD Battle Command System (IBCS) under the Air Defense Systems Integration IDIQ. Work includes sensor-to-shooter integration testing, software release engineering, and test range support.",
    requirements: JSON.stringify(["IBCS/IAMD experience", "Software integration testing", "TS/SCI clearance required", "DCSA FOCI cleared facility"]),
    naicsCode: "541511",
    setAside: "Unrestricted",
    valueMin: 45000000,
    valueMax: 72000000,
    dueDate: new Date("2026-08-05"),
    pob: "Redstone Arsenal, AL / White Sands Missile Range, NM",
    securityClear: "TS/SCI",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0008",
    title: "Explosive Ordnance Disposal Training Support — Eglin AFB",
    agency: "Department of the Army",
    subAgency: "Combined Arms Support Command",
    description: "Task order for EOD training course development, instruction, and simulation system maintenance at Eglin AFB EOD School under the Army Training Support IDIQ. Deliverables include updated curricula for RCIED and IED defeat techniques.",
    requirements: JSON.stringify(["EOD MOS qualified personnel", "Classified training development", "SECRET clearance minimum", "Eglin AFB access"]),
    naicsCode: "611699",
    setAside: "SDVOSB",
    valueMin: 7000000,
    valueMax: 13000000,
    dueDate: new Date("2026-07-20"),
    pob: "Eglin AFB, FL",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0007",
    title: "Tactical Network Modernization — WIN-T Sustainment",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Command, Control, Communications-Tactical",
    description: "Lifecycle sustainment and capability upgrade task order for Warfighter Information Network-Tactical (WIN-T) under the PEO C3T IDIQ. Scope includes network management software, hardware obsolescence management, and transition support to Unified Network.",
    requirements: JSON.stringify(["WIN-T platform expertise", "Tactical communications background", "SECRET clearance", "SATCOM/LOS transport experience"]),
    naicsCode: "517311",
    setAside: "SB",
    valueMin: 20000000,
    valueMax: 35000000,
    dueDate: new Date("2026-06-25"),
    pob: "Aberdeen Proving Ground, MD",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0009",
    title: "Waterway Infrastructure Assessment — Mississippi River",
    agency: "Department of the Army",
    subAgency: "US Army Corps of Engineers — MVD",
    description: "Structural condition assessment task order for lock and dam infrastructure on the upper Mississippi River under the USACE Infrastructure Assessment IDIQ. Deliverables include underwater inspection reports, structural analysis, and prioritized repair recommendations.",
    requirements: JSON.stringify(["Underwater structural inspection", "USACE dam safety standards", "PE (Civil/Structural) licensed", "Diving operations certified"]),
    naicsCode: "237990",
    setAside: "HUBZone",
    valueMin: 9000000,
    valueMax: 16000000,
    dueDate: new Date("2026-09-10"),
    pob: "Upper Mississippi River District",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0008",
    title: "Soldier Lethality Technology Integration — Next Gen Squad Weapon",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Soldier",
    description: "Systems engineering and test support task order for Next Generation Squad Weapon and fire control integration under the Soldier Systems IDIQ. Work includes ballistic testing, soldier load analysis, and human factors research at Natick Soldier RD&E Center.",
    requirements: JSON.stringify(["Small arms systems expertise", "Live-fire test support capability", "Ballistics engineering background", "SECRET clearance"]),
    naicsCode: "332994",
    setAside: "Unrestricted",
    valueMin: 15000000,
    valueMax: 28000000,
    dueDate: new Date("2026-08-10"),
    pob: "Natick, MA / Aberdeen Proving Ground, MD",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0010",
    title: "Range Instrumentation & Telemetry Modernization — Dugway",
    agency: "Department of the Army",
    subAgency: "US Army Test & Evaluation Command",
    description: "Design, installation, and integration task order for next-generation range instrumentation and telemetry systems at Dugway Proving Ground under the ATEC Range Modernization IDIQ. Systems include multi-spectral cameras, radar trackers, and secure data links.",
    requirements: JSON.stringify(["Range instrumentation expertise", "Telemetry system design", "SECRET clearance minimum", "TS/SCI for some tasks"]),
    naicsCode: "334511",
    setAside: "Unrestricted",
    valueMin: 22000000,
    valueMax: 38000000,
    dueDate: new Date("2026-07-30"),
    pob: "Dugway Proving Ground, UT",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0009",
    title: "Army Futures Command Research Analytics Support",
    agency: "Department of the Army",
    subAgency: "Army Futures Command",
    description: "Data analytics, operations research, and wargaming support task order for Army Futures Command Cross-Functional Teams under the AFC Analysis IDIQ. Work supports modernization prioritization across the six CFT domains.",
    requirements: JSON.stringify(["Army modernization domain expertise", "OR/SA with defense background", "TS/SCI clearance preferred", "Wargame design experience"]),
    naicsCode: "541690",
    setAside: "Unrestricted",
    valueMin: 28000000,
    valueMax: 48000000,
    dueDate: new Date("2026-06-10"),
    pob: "Austin, TX",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0011",
    title: "Emergency Management Training & Exercise — NORTHCOM",
    agency: "Department of the Army",
    subAgency: "US Northern Command",
    description: "Exercise planning, execution, and evaluation task order for NORTHCOM homeland defense and civil support exercises under the HSEEP-compliant Exercise Support IDIQ. Deliverables include scenario design, controller/evaluator support, and after-action reports.",
    requirements: JSON.stringify(["HSEEP Master Trainer certification", "Homeland defense exercise background", "SECRET clearance", "NORTHCOM exercise experience"]),
    naicsCode: "541990",
    setAside: "SB",
    valueMin: 5000000,
    valueMax: 10000000,
    dueDate: new Date("2026-08-25"),
    pob: "Peterson SFB, CO",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0010",
    title: "CBRN Detection System Fielding & Training",
    agency: "Department of the Army",
    subAgency: "Program Executive Office CBRN & Radiological Sensors",
    description: "System fielding, new equipment training, and sustainment task order for Joint Chemical Agent Detector (JCAD) and Joint Biological Point Detection System under the CBRN Sensors IDIQ. Scope includes 48 unit fieldings and 200 sustainment maintenance events.",
    requirements: JSON.stringify(["CBRN sensor systems expertise", "New equipment fielding experience", "SECRET clearance minimum", "CBRN master trainer qualification"]),
    naicsCode: "334516",
    setAside: "Unrestricted",
    valueMin: 16000000,
    valueMax: 27000000,
    dueDate: new Date("2026-07-05"),
    pob: "Fort Leonard Wood, MO / CONUS/OCONUS Units",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0012",
    title: "Military Housing Privatization Program Support",
    agency: "Department of the Army",
    subAgency: "Installation Management Command",
    description: "Program management and financial oversight support task order for Army Residential Communities Initiative privatized housing projects under the AHRP Support IDIQ. Services include lease compliance auditing, resident relations support, and capital planning review.",
    requirements: JSON.stringify(["Military housing privatization experience", "Real estate finance background", "IMCOM policy compliance", "PII data handling"]),
    naicsCode: "531311",
    setAside: "WOSB",
    valueMin: 8000000,
    valueMax: 14000000,
    dueDate: new Date("2026-06-05"),
    pob: "Multiple Army Installations (Nationwide)",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0011",
    title: "Electronic Warfare Reprogramming Support — EWIR Database",
    agency: "Department of the Army",
    subAgency: "Army Electronic Warfare Division",
    description: "Electronic warfare reprogramming, software development, and database management task order for Army platform EW systems under the EWIR IDIQ. Work includes threat parameter updates, reprogramming production, and flight test validation.",
    requirements: JSON.stringify(["EW reprogramming experience", "ECM system software", "TS/SCI with CI Poly clearance", "EWIR database management"]),
    naicsCode: "541511",
    setAside: "Unrestricted",
    valueMin: 35000000,
    valueMax: 58000000,
    dueDate: new Date("2026-09-20"),
    pob: "Fort Gordon, GA",
    securityClear: "TS/SCI",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "W912DR-26-T-0013",
    title: "Bridge & Structure Inspection — USACE Civil Works",
    agency: "Department of the Army",
    subAgency: "US Army Corps of Engineers",
    description: "Bridge and infrastructure condition inspection task order for USACE-maintained structures under the Civil Works Inspection IDIQ. Deliverables include AASHTO-compliant inspection reports, load ratings, and NBI data submissions for 450+ structures.",
    requirements: JSON.stringify(["FHWA Bridge Inspector qualification", "NBI data management", "USACE civil works experience", "Underwater inspection certification"]),
    naicsCode: "541330",
    setAside: "8(a)",
    valueMin: 6000000,
    valueMax: 11000000,
    dueDate: new Date("2026-07-18"),
    pob: "USACE Civil Works Districts (Nationwide)",
    securityClear: "None",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
  {
    solicNumber: "DAAH23-26-T-0012",
    title: "Army AI/ML Autonomous Systems Prototype Development",
    agency: "Department of the Army",
    subAgency: "Army Futures Command — AI Task Force",
    description: "Prototype development task order for AI/ML-enabled autonomous logistics and reconnaissance systems under the Army xTechSearch IDIQ. Deliverables include software-defined autonomy modules, simulation-based validation, and TRL 5-6 field demonstrations.",
    requirements: JSON.stringify(["AI/ML autonomy development", "Edge computing integration", "SECRET clearance", "Army IVAS/xTechSearch experience"]),
    naicsCode: "541715",
    setAside: "SB",
    valueMin: 10000000,
    valueMax: 18000000,
    dueDate: new Date("2026-08-30"),
    pob: "Austin, TX / Field Test Sites",
    securityClear: "Secret",
    type: "IDIQ",
    vehicleType: "IDIQ",
  },
];

const otaContracts = [
  {
    solicNumber: "W15QKN-26-9-0001",
    title: "Hypersonic Glide Vehicle Thermal Protection Prototype",
    agency: "Department of the Army",
    subAgency: "Army Rapid Capabilities & Critical Technologies Office",
    description: "Other Transaction Agreement for prototype development of next-generation thermal protection systems for Army hypersonic glide vehicles. Performer shall demonstrate TRL 6 thermal materials under realistic re-entry heat flux conditions in wind tunnel and sled tests.",
    requirements: JSON.stringify(["Hypersonic TPS development experience", "High-temperature materials testing", "TS/SCI clearance required", "Mach 15+ thermal environment capability"]),
    naicsCode: "336414",
    setAside: "Unrestricted",
    valueMin: 40000000,
    valueMax: 70000000,
    dueDate: new Date("2026-06-30"),
    pob: "Redstone Arsenal, AL / White Sands, NM",
    securityClear: "TS/SCI",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0002",
    title: "Soldier-Wearable Exoskeleton Mobility Prototype",
    agency: "Department of the Army",
    subAgency: "Army Futures Command — Soldier Lethality CFT",
    description: "OTA prototype agreement for powered exoskeleton system reducing soldier physical burden during dismounted operations. Performer shall achieve 30% fatigue reduction in standardized loaded march while adding no more than 8 lbs to the soldier's load.",
    requirements: JSON.stringify(["Exoskeleton/wearable robotics experience", "Human performance testing capability", "MIL-STD-810 environmental testing", "Soldier systems integration background"]),
    naicsCode: "339113",
    setAside: "Unrestricted",
    valueMin: 15000000,
    valueMax: 28000000,
    dueDate: new Date("2026-07-15"),
    pob: "Natick, MA",
    securityClear: "None",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0001",
    title: "Next-Generation Biometric Identity Management Prototype",
    agency: "Department of Defense",
    subAgency: "Defense Human Resources Activity",
    description: "Prototype OTA for multimodal biometric identity management system incorporating iris, face, fingerprint, and gait recognition for access control at sensitive DoD facilities. System shall achieve FAR <0.001% and FRR <1% under operational conditions.",
    requirements: JSON.stringify(["Multimodal biometric systems experience", "NIST FRVT top-tier performance", "SECRET facility clearance", "PIV/CAC integration capability"]),
    naicsCode: "541512",
    setAside: "Unrestricted",
    valueMin: 20000000,
    valueMax: 38000000,
    dueDate: new Date("2026-08-01"),
    pob: "Arlington, VA",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0003",
    title: "Urban Air Mobility Logistics Drone Prototype",
    agency: "Department of the Army",
    subAgency: "Army Futures Command — Aviation & Missile CFT",
    description: "OTA prototype for unmanned aerial logistics vehicle capable of delivering 500 lb payloads within dense urban environments for last-tactical-mile resupply. Performer shall demonstrate autonomous obstacle avoidance, GPS-denied navigation, and vertical takeoff/landing.",
    requirements: JSON.stringify(["Heavy-lift UAS development", "GPS-denied autonomous navigation", "FAA Part 107 compliance path", "MIL-STD environmental qualification"]),
    naicsCode: "336411",
    setAside: "Unrestricted",
    valueMin: 25000000,
    valueMax: 45000000,
    dueDate: new Date("2026-09-01"),
    pob: "Redstone Arsenal, AL / Urban Test Sites",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0002",
    title: "Synthetic Training Environment Immersive Prototype",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Simulation, Training & Instrumentation",
    description: "OTA agreement for immersive synthetic training environment leveraging photorealistic rendering, haptic feedback, and AI-driven opposing forces for collective training at company level. System shall integrate with ONE Synthetic Training Environment architecture.",
    requirements: JSON.stringify(["Game engine military simulation (Unreal/Unity)", "Network-based collective training experience", "Haptic/XR hardware integration", "ONE STE architecture knowledge"]),
    naicsCode: "611699",
    setAside: "SB",
    valueMin: 18000000,
    valueMax: 32000000,
    dueDate: new Date("2026-07-20"),
    pob: "Orlando, FL",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0004",
    title: "Quantum Key Distribution Communication Prototype",
    agency: "Department of the Army",
    subAgency: "Army Research Laboratory",
    description: "Research and prototype OTA for tactical quantum key distribution (QKD) communication systems capable of field deployment in a tactical vehicle. Performer shall demonstrate quantum-secured key exchange over free-space optical links at 10km range.",
    requirements: JSON.stringify(["Quantum photonics expertise", "Free-space optical communication", "Cryptographic module engineering", "TS/SCI clearance for some tasks"]),
    naicsCode: "541715",
    setAside: "Unrestricted",
    valueMin: 12000000,
    valueMax: 22000000,
    dueDate: new Date("2026-06-15"),
    pob: "Adelphi, MD",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0003",
    title: "Personnel Recovery AI Decision Support Prototype",
    agency: "Department of Defense",
    subAgency: "Joint Personnel Recovery Agency",
    description: "OTA prototype for AI-enabled decision support tool for joint personnel recovery mission planning, integrating multi-source ISR data with terrain analysis, threat modeling, and route optimization for search and rescue operations.",
    requirements: JSON.stringify(["Personnel recovery doctrine knowledge", "AI/ML mission planning tools", "TS/SCI clearance required", "JPRA exercise participation"]),
    naicsCode: "541511",
    setAside: "Unrestricted",
    valueMin: 8000000,
    valueMax: 16000000,
    dueDate: new Date("2026-08-15"),
    pob: "Fairchild AFB, WA",
    securityClear: "TS/SCI",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0005",
    title: "Long-Range Precision Fires Guidance Modernization",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Missiles & Space",
    description: "OTA prototype agreement for modernized guidance, navigation, and control for Extended Range Cannon Artillery (ERCA) Excalibur munitions improving accuracy to <1m CEP at 70km range. Performer shall integrate multi-mode seeker with existing guidance section.",
    requirements: JSON.stringify(["Precision munitions guidance experience", "INS/GPS integration for munitions", "Environmental test hardening (20,000g setback)", "Secret clearance minimum"]),
    naicsCode: "332993",
    setAside: "Unrestricted",
    valueMin: 35000000,
    valueMax: 60000000,
    dueDate: new Date("2026-07-10"),
    pob: "Huntsville, AL / Yuma Proving Ground, AZ",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0004",
    title: "Directed Energy Counter-UAS Prototype — 50kW Laser",
    agency: "Department of the Army",
    subAgency: "Army Rapid Capabilities & Critical Technologies Office",
    description: "OTA prototype for 50kW-class solid-state laser system for counter-UAS applications mounted on an Armored Multi-Purpose Vehicle. Performer shall demonstrate lethality against Group 1-3 UAS at 1km range with <5 second engagement timelines.",
    requirements: JSON.stringify(["High energy laser systems", "AMPU/vehicle integration", "DE safety range protocols", "TS/SCI clearance preferred"]),
    naicsCode: "334511",
    setAside: "Unrestricted",
    valueMin: 55000000,
    valueMax: 90000000,
    dueDate: new Date("2026-09-15"),
    pob: "White Sands Missile Range, NM",
    securityClear: "TS/SCI",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0006",
    title: "Tactical Mesh Network 5G Prototype — Multi-Domain Operations",
    agency: "Department of the Army",
    subAgency: "Army Futures Command — Network CFT",
    description: "OTA prototype for 5G-enabled tactical mesh networking system supporting multi-domain operations data throughput requirements. System must sustain 10 Gbps aggregate throughput across a 20-node mobile mesh in contested electronic warfare environment.",
    requirements: JSON.stringify(["5G/mesh network development", "EW-resilient communications", "Army tactical network architecture", "SECRET clearance"]),
    naicsCode: "517311",
    setAside: "SB",
    valueMin: 20000000,
    valueMax: 36000000,
    dueDate: new Date("2026-08-20"),
    pob: "Aberdeen Proving Ground, MD",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0005",
    title: "Predictive Health Monitoring Wearable — Soldier Readiness",
    agency: "Department of Defense",
    subAgency: "Defense Health Agency",
    description: "OTA prototype for soldier physiological monitoring wearable integrating continuous biomarker tracking (cortisol, lactate, hydration) with AI-driven fatigue prediction to support readiness decision-making by unit commanders.",
    requirements: JSON.stringify(["Wearable biosensor development", "Real-time physiological analytics", "HIPAA/DoD privacy compliance", "Clinical validation methodology"]),
    naicsCode: "334510",
    setAside: "Unrestricted",
    valueMin: 10000000,
    valueMax: 18000000,
    dueDate: new Date("2026-06-25"),
    pob: "Fort Sam Houston, TX",
    securityClear: "None",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0007",
    title: "Autonomous Ground Resupply Vehicle Prototype",
    agency: "Department of the Army",
    subAgency: "Army Futures Command — Soldier Lethality CFT",
    description: "OTA prototype for optionally-manned, fully autonomous ground resupply vehicle capable of 1-ton payload delivery over 50km in complex terrain without GPS. Performer shall demonstrate leader-follower formation and autonomous navigation through simulated contested route.",
    requirements: JSON.stringify(["Autonomous ground vehicle development", "Multi-vehicle convoy algorithms", "MIL-STD-1275 power interface", "SECRET clearance preferred"]),
    naicsCode: "336120",
    setAside: "Unrestricted",
    valueMin: 30000000,
    valueMax: 50000000,
    dueDate: new Date("2026-07-25"),
    pob: "Fort Leonard Wood, MO / Camp Grayling, MI",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0006",
    title: "Space Domain Awareness Machine Learning Prototype",
    agency: "Department of the Air Force",
    subAgency: "Space Systems Command",
    description: "OTA prototype for machine learning-based space domain awareness system detecting and characterizing maneuvers by adversary satellites using ground-based optical and radar data. System shall support automated threat warning cueing to Space Operations Command.",
    requirements: JSON.stringify(["Space domain awareness expertise", "ML anomaly detection for space objects", "TS/SCI clearance required", "Astrodynamics background"]),
    naicsCode: "541715",
    setAside: "Unrestricted",
    valueMin: 25000000,
    valueMax: 42000000,
    dueDate: new Date("2026-08-10"),
    pob: "El Segundo, CA / Peterson SFB, CO",
    securityClear: "TS/SCI",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0008",
    title: "Counter-Drone Electronic Attack Prototype — Squad Level",
    agency: "Department of the Army",
    subAgency: "Army Rapid Capabilities & Critical Technologies Office",
    description: "OTA prototype for squad-portable counter-drone electronic attack system capable of defeating Groups 1-2 UAS through jamming and spoofing within a 3km radius. System weight shall not exceed 15 lbs and must operate on standard Army battery logistics.",
    requirements: JSON.stringify(["Portable EW/EA development", "UAS defeat demonstration history", "RF engineering expertise", "SECRET clearance"]),
    naicsCode: "334220",
    setAside: "SB",
    valueMin: 8000000,
    valueMax: 15000000,
    dueDate: new Date("2026-06-10"),
    pob: "Redstone Arsenal, AL",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0007",
    title: "Cyber Vulnerability Automated Discovery Prototype",
    agency: "Department of Defense",
    subAgency: "US Cyber Command",
    description: "OTA prototype for automated vulnerability discovery and exploitation tool for DoD offensive cyber operations mission support. Performer shall demonstrate novel capability against emulated target systems with measurable improvement over existing tradecraft.",
    requirements: JSON.stringify(["Offensive cyber R&D background", "Vulnerability research expertise", "TS/SCI with Full Scope Poly", "CNMF/USCYBERCOM relationship preferred"]),
    naicsCode: "541519",
    setAside: "Unrestricted",
    valueMin: 18000000,
    valueMax: 32000000,
    dueDate: new Date("2026-09-05"),
    pob: "Fort Meade, MD",
    securityClear: "TS/SCI",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0009",
    title: "Optionally-Manned Fighting Vehicle Autonomy Integration",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Ground Combat Systems",
    description: "OTA prototype for autonomy kit enabling OMFV platform to operate in leader-follower mode under remote supervision. Performer shall integrate perception, planning, and control software with the candidate OMFV hull, demonstrating Level 2B autonomy across complex terrain.",
    requirements: JSON.stringify(["Ground combat vehicle autonomy", "ROS2/DDS middleware integration", "High payload autonomous navigation", "SECRET clearance minimum"]),
    naicsCode: "336992",
    setAside: "Unrestricted",
    valueMin: 45000000,
    valueMax: 75000000,
    dueDate: new Date("2026-08-05"),
    pob: "Warren, MI / Fort Bliss, TX",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0008",
    title: "Nuclear Radiation Detection Miniaturized Prototype",
    agency: "Department of Defense",
    subAgency: "Defense Threat Reduction Agency",
    description: "OTA prototype for miniaturized radiation detection module suitable for integration into commercial smartphones for wide-area radiological monitoring. Performer shall achieve sensitivity equivalent to current RIID systems at 1/100th the form factor.",
    requirements: JSON.stringify(["Nuclear/radiological detection physics", "Miniaturized sensor development", "ANSI N42 performance standards", "TS/SCI for classified applications"]),
    naicsCode: "334516",
    setAside: "Unrestricted",
    valueMin: 12000000,
    valueMax: 22000000,
    dueDate: new Date("2026-07-01"),
    pob: "Fort Belvoir, VA",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0010",
    title: "Persistent Surveillance Aerostat Prototype — TARS Replacement",
    agency: "Department of the Army",
    subAgency: "Army Space & Missile Defense Command",
    description: "OTA prototype for next-generation tethered aerostat radar system replacing aging TARS installations at the southern border. Prototype shall demonstrate 72-hour continuous operations at 15,000 ft AGL with AESA radar payload and EO/IR sensor suite.",
    requirements: JSON.stringify(["Aerostat/tethered balloon systems", "AESA radar integration", "Long-duration operations experience", "SECRET clearance"]),
    naicsCode: "336411",
    setAside: "Unrestricted",
    valueMin: 28000000,
    valueMax: 50000000,
    dueDate: new Date("2026-09-20"),
    pob: "Multiple TARS Sites (Southwest Border)",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0009",
    title: "AI-Enabled Threat Intelligence Fusion Prototype",
    agency: "Department of Defense",
    subAgency: "Defense Intelligence Agency",
    description: "OTA prototype for AI-driven all-source intelligence fusion platform aggregating HUMINT, SIGINT, GEOINT, and OSINT data streams to produce predictive threat assessments. System shall demonstrate improved analyst throughput by 40% in competitive red team evaluation.",
    requirements: JSON.stringify(["All-source intelligence analytics", "NLP/ML for OSINT exploitation", "TS/SCI with CI Poly clearance", "DIA system architecture familiarity"]),
    naicsCode: "541511",
    setAside: "Unrestricted",
    valueMin: 22000000,
    valueMax: 40000000,
    dueDate: new Date("2026-06-20"),
    pob: "Bethesda, MD",
    securityClear: "TS/SCI",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0011",
    title: "Soldier Power Management Energy Harvesting Prototype",
    agency: "Department of the Army",
    subAgency: "Army Research, Development & Engineering Command",
    description: "OTA prototype for multi-source energy harvesting system integrated into soldier load-bearing equipment capturing kinetic, thermal, and photovoltaic energy to extend battery life by 50% in deployed operations.",
    requirements: JSON.stringify(["Energy harvesting technology", "Wearable power management", "RDECOM collaboration history preferred", "MIL-STD-810 qualification testing"]),
    naicsCode: "335911",
    setAside: "SB",
    valueMin: 6000000,
    valueMax: 12000000,
    dueDate: new Date("2026-07-30"),
    pob: "Adelphi, MD / Fort Devens, MA",
    securityClear: "None",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0010",
    title: "Hypersonic Defense Kill Chain Automation Prototype",
    agency: "Department of the Air Force",
    subAgency: "Air Force Research Laboratory",
    description: "OTA prototype for sensing and kill chain automation enabling engagement of hypersonic glide vehicles by existing ground-based interceptors. Performer shall demonstrate end-to-end kill chain from detection to intercept in hardware-in-the-loop simulation.",
    requirements: JSON.stringify(["Hypersonic target tracking algorithms", "Kill chain automation software", "TS/SCI clearance required", "Missile engagement simulation experience"]),
    naicsCode: "541715",
    setAside: "Unrestricted",
    valueMin: 35000000,
    valueMax: 62000000,
    dueDate: new Date("2026-08-25"),
    pob: "Wright-Patterson AFB, OH",
    securityClear: "TS/SCI",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0012",
    title: "Advanced Body Armor Composite Material Prototype",
    agency: "Department of the Army",
    subAgency: "PEO Soldier — PM Soldier Protection & Individual Equipment",
    description: "OTA prototype for next-generation ceramic-polymer composite body armor plate achieving Level IV protection with 20% weight reduction versus current ESAPI. Performer shall conduct ballistic acceptance testing per MIL-DTL-46100 and NIJ Standard-0101.07.",
    requirements: JSON.stringify(["Advanced composite armor development", "NIJ/MIL ballistic testing capability", "Ceramic/polymer materials science", "Manufacturing scale-up plan"]),
    naicsCode: "332993",
    setAside: "Unrestricted",
    valueMin: 14000000,
    valueMax: 25000000,
    dueDate: new Date("2026-06-05"),
    pob: "Natick, MA / Aberdeen Proving Ground, MD",
    securityClear: "None",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0011",
    title: "Maritime Domain Awareness AI Fusion Engine Prototype",
    agency: "Department of the Navy",
    subAgency: "Office of Naval Research",
    description: "OTA prototype for AI-powered maritime domain awareness fusion engine integrating AIS, satellite imagery, radar, and acoustic data to detect and characterize anomalous vessel behavior in contested littoral zones.",
    requirements: JSON.stringify(["Maritime sensor fusion experience", "Anomaly detection algorithms", "SECRET clearance minimum", "ONR program office collaboration"]),
    naicsCode: "541715",
    setAside: "Unrestricted",
    valueMin: 16000000,
    valueMax: 30000000,
    dueDate: new Date("2026-09-10"),
    pob: "Arlington, VA / Stennis Space Center, MS",
    securityClear: "Secret",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "W15QKN-26-9-0013",
    title: "Rapid Airfield Damage Repair Material Prototype",
    agency: "Department of the Air Force",
    subAgency: "Air Force Civil Engineer Center",
    description: "OTA prototype for rapid-setting polymer concrete airfield repair material enabling C-17 operations within 2 hours of crater repair in contested environment. Performer shall demonstrate cure strength of 3,000 psi at 2 hours ambient temperature down to -20F.",
    requirements: JSON.stringify(["Rapid-cure construction materials", "Airfield pavement engineering", "Cold weather performance testing", "Air Force CE familiarity"]),
    naicsCode: "327320",
    setAside: "SB",
    valueMin: 5000000,
    valueMax: 10000000,
    dueDate: new Date("2026-07-12"),
    pob: "Tyndall AFB, FL / Multiple Test Sites",
    securityClear: "None",
    type: "OTA",
    vehicleType: "OTA",
  },
  {
    solicNumber: "HROO11-26-9-0012",
    title: "Multi-Domain Command & Control Interface Prototype",
    agency: "Department of the Army",
    subAgency: "Army Futures Command — Mission Command CFT",
    description: "OTA prototype for multi-domain command and control interface enabling joint force commanders to visualize and direct operations across land, air, sea, space, and cyberspace domains simultaneously. Prototype shall integrate with JADC2 architecture and support AI-assisted decision recommendations.",
    requirements: JSON.stringify(["Multi-domain C2 systems experience", "JADC2 architecture knowledge", "TS/SCI clearance required", "Human-machine teaming interface design"]),
    naicsCode: "541511",
    setAside: "Unrestricted",
    valueMin: 30000000,
    valueMax: 55000000,
    dueDate: new Date("2026-08-30"),
    pob: "Fort Leavenworth, KS / Austin, TX",
    securityClear: "TS/SCI",
    type: "OTA",
    vehicleType: "OTA",
  },
];

const gsaContracts = [
  {
    solicNumber: "GS-35F-26R-0001",
    title: "Zero Trust Architecture Implementation — Civilian Agency Enterprise",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — IT Category",
    description: "Enterprise Zero Trust security architecture design and implementation for civilian federal agencies through the GSA IT Schedule 70 / MAS program. Work includes identity management, micro-segmentation, device trust, and continuous monitoring aligned with OMB M-22-09.",
    requirements: JSON.stringify(["GSA MAS Schedule holder (SIN 54151S)", "Zero Trust architecture certification", "CISA ZTMM alignment experience", "FedRAMP Authorized solution portfolio"]),
    naicsCode: "541512",
    setAside: "Unrestricted",
    valueMin: 0,
    valueMax: 750000000,
    dueDate: new Date("2026-06-30"),
    pob: "Nationwide (Civilian Agencies)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0001",
    title: "Cloud Managed Services — GSA Alliant 3 Task Order",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service",
    description: "Comprehensive cloud managed services task order under GSA Alliant 3 GWAC covering cloud operations, optimization, FinOps, and managed security for a multi-agency customer. Services span AWS GovCloud, Azure Government, and Google Public Sector environments.",
    requirements: JSON.stringify(["Alliant 3 contract holder", "Multi-cloud managed services", "FedRAMP High authorization", "FinOps Certified Practitioner"]),
    naicsCode: "541519",
    setAside: "Unrestricted",
    valueMin: 50000000,
    valueMax: 150000000,
    dueDate: new Date("2026-07-15"),
    pob: "Washington, DC / Remote",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0002",
    title: "Data Analytics Platform — Federal Statistical Agency Modernization",
    agency: "General Services Administration",
    subAgency: "Technology Transformation Services",
    description: "Data analytics platform modernization through 18F and Login.gov partnerships for federal statistical agencies replacing legacy SAS/SPSS workflows with cloud-native analytics and self-service business intelligence tools.",
    requirements: JSON.stringify(["Federal data governance experience", "Cloud-native analytics platforms (Databricks/Snowflake)", "GSA MAS Schedule holder", "Section 508 compliance"]),
    naicsCode: "541511",
    setAside: "WOSB",
    valueMin: 8000000,
    valueMax: 20000000,
    dueDate: new Date("2026-08-01"),
    pob: "Washington, DC (Hybrid)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0002",
    title: "Enterprise Resource Planning Modernization — GWAC Task Order",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service",
    description: "ERP modernization task order under GSA Alliant 2 for a large cabinet-level agency transitioning from Oracle E-Business Suite to SAP S/4HANA Cloud. Project covers financial management, HR, procurement, and asset management modules with FedRAMP authorization.",
    requirements: JSON.stringify(["SAP S/4HANA federal implementation", "Oracle EBS migration experience", "Alliant 2 / Alliant 3 contract holder", "FedRAMP Moderate/High path"]),
    naicsCode: "541512",
    setAside: "SB",
    valueMin: 35000000,
    valueMax: 80000000,
    dueDate: new Date("2026-06-15"),
    pob: "Washington, DC",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0003",
    title: "Artificial Intelligence / Machine Learning Platform Services",
    agency: "General Services Administration",
    subAgency: "Office of GSA IT",
    description: "AI/ML platform services for government agencies through the GSA MAS program including model development, MLOps infrastructure, responsible AI governance frameworks, and bias testing services for high-impact federal AI applications.",
    requirements: JSON.stringify(["GSA MAS SIN 54151AI holder", "Responsible AI governance framework", "NIST AI RMF alignment", "FedRAMP authorized AI platform"]),
    naicsCode: "541511",
    setAside: "8(a)",
    valueMin: 5000000,
    valueMax: 25000000,
    dueDate: new Date("2026-09-01"),
    pob: "Nationwide",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0003",
    title: "Cybersecurity Shared Services — CISA CDM Program Support",
    agency: "Department of Homeland Security",
    subAgency: "CISA Continuous Diagnostics & Mitigation Program",
    description: "Continuous Diagnostics and Mitigation shared services delivery under GSA/CISA CDM DEFEND Group C task order covering asset management, identity management, network management, and data protection for civilian agencies.",
    requirements: JSON.stringify(["CDM DEFEND awardee (Group C)", "CDM tool integration expertise", "FedRAMP High authorized CDM tools", "CISA program office relationship"]),
    naicsCode: "541519",
    setAside: "Unrestricted",
    valueMin: 80000000,
    valueMax: 200000000,
    dueDate: new Date("2026-07-30"),
    pob: "Arlington, VA / Agency Sites Nationwide",
    securityClear: "Secret",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0004",
    title: "IT Help Desk & End-User Computing Support — Multiple Award",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — IT Category",
    description: "Enterprise IT help desk and end-user computing support services through GSA MAS Schedule covering Tier 1-3 support, device management, ITSM platform operations, and remote support for federal civilian agency customers.",
    requirements: JSON.stringify(["GSA MAS Schedule 70 holder", "ITIL v4 certified workforce", "ServiceNow/Remedy ITSM experience", "Federal help desk SLA compliance"]),
    naicsCode: "561422",
    setAside: "SDVOSB",
    valueMin: 10000000,
    valueMax: 40000000,
    dueDate: new Date("2026-06-10"),
    pob: "Nationwide (Hybrid/Remote)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0004",
    title: "Agile Software Development — Human-Centered Design Services",
    agency: "General Services Administration",
    subAgency: "Technology Transformation Services / 18F",
    description: "Human-centered design and agile software development task order through GSA 8(a) STARS III to modernize a public-facing federal benefits portal. Deliverables include user research, iterative prototyping, accessibility remediation, and launch of re-engineered portal.",
    requirements: JSON.stringify(["8(a) STARS III contract holder", "Human-centered design methodology", "USWDS / federal design system experience", "Section 508 / WCAG 2.1 AA compliance"]),
    naicsCode: "541511",
    setAside: "8(a)",
    valueMin: 12000000,
    valueMax: 30000000,
    dueDate: new Date("2026-08-15"),
    pob: "Washington, DC (Remote-First)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0005",
    title: "Network Operations & Managed Security — EIS Contract",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — Network Services Program",
    description: "Managed network and security services under the Enterprise Infrastructure Solutions (EIS) contract supporting multi-agency network operations centers, SD-WAN deployment, and 24/7 managed detection and response services.",
    requirements: JSON.stringify(["EIS contract holder", "SD-WAN federal implementation", "MDR/SOC services capability", "MTIPS/TIC 3.0 compliance"]),
    naicsCode: "517311",
    setAside: "Unrestricted",
    valueMin: 100000000,
    valueMax: 500000000,
    dueDate: new Date("2026-09-15"),
    pob: "Nationwide (All Federal Agencies)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0005",
    title: "Digital Transformation Advisory — CXO Council Support",
    agency: "General Services Administration",
    subAgency: "Office of the CIO",
    description: "Strategic advisory and program management support for government-wide digital transformation initiatives through the GSA Professional Services Schedule. Work supports Federal CIO Council, CDO Council, and CISO Council working groups on cross-agency IT policy.",
    requirements: JSON.stringify(["Federal IT policy expertise", "GSA PSS Schedule holder", "CIO/CDO Council engagement experience", "OMB circular compliance advisory"]),
    naicsCode: "541611",
    setAside: "SB",
    valueMin: 6000000,
    valueMax: 15000000,
    dueDate: new Date("2026-07-01"),
    pob: "Washington, DC (Hybrid)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0006",
    title: "Section 508 Accessibility Testing & Remediation Services",
    agency: "General Services Administration",
    subAgency: "Government-wide IT Accessibility Program",
    description: "IT accessibility testing, remediation, and training services through GSA MAS for federal agencies to achieve Section 508 compliance. Services include automated and manual accessibility audits, VPAT generation, and developer training.",
    requirements: JSON.stringify(["DHS Trusted Tester certification", "WCAG 2.1 AA/AAA expertise", "GSA MAS Schedule holder", "Federal accessibility policy knowledge"]),
    naicsCode: "541519",
    setAside: "WOSB",
    valueMin: 2000000,
    valueMax: 8000000,
    dueDate: new Date("2026-06-20"),
    pob: "Nationwide (Remote-Capable)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0006",
    title: "Federal Acquisition Category Management Analytics",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — Category Management PMO",
    description: "Category management analytics and shared services support task order under GSA OASIS+ providing spend analytics, supplier diversity reporting, strategic sourcing support, and category management training to agency acquisition professionals.",
    requirements: JSON.stringify(["OASIS+ contract holder", "Federal category management background", "GSA eBuy/SAM.gov expertise", "Supplier diversity analytics"]),
    naicsCode: "541611",
    setAside: "Unrestricted",
    valueMin: 8000000,
    valueMax: 18000000,
    dueDate: new Date("2026-08-10"),
    pob: "Washington, DC",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0007",
    title: "Identity, Credential & Access Management — Federal Workforce",
    agency: "General Services Administration",
    subAgency: "Office of Government-wide Policy",
    description: "ICAM shared services for federal agencies through GSA MAS covering PIV credential management, enterprise SSO, privileged access management, and FIDO2 authentication deployment aligned with EO 14028 requirements.",
    requirements: JSON.stringify(["Federal ICAM architecture experience", "PIV/PIV-I implementation", "GSA MAS holder (SIN 54151S)", "FICAM roadmap alignment"]),
    naicsCode: "541512",
    setAside: "HUBZone",
    valueMin: 15000000,
    valueMax: 40000000,
    dueDate: new Date("2026-07-20"),
    pob: "Washington, DC / Agency Sites",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0007",
    title: "Robotic Process Automation Deployment — GWAC BPA",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — Technology Programs",
    description: "RPA deployment and CoE services blanket purchase agreement under GSA Alliant 2/3 for enterprise automation of manual data processing in federal back-office operations. BPA covers RPA bot development, attended/unattended automation, and intelligent document processing.",
    requirements: JSON.stringify(["Alliant 2 or 3 contract holder", "UiPath/Automation Anywhere/Blue Prism", "Federal RPA CoE experience", "Process mining capability"]),
    naicsCode: "541512",
    setAside: "SB",
    valueMin: 20000000,
    valueMax: 60000000,
    dueDate: new Date("2026-06-25"),
    pob: "Nationwide (Federal Agencies)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0008",
    title: "Open Source Intelligence & Social Media Monitoring Services",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — Human Capital & Training Solutions",
    description: "OSINT collection, social media monitoring, and threat intelligence services through GSA MAS for federal law enforcement and security agencies. Services include dark web monitoring, brand protection, and analyst training.",
    requirements: JSON.stringify(["OSINT platform provision experience", "Dark web monitoring capability", "GSA MAS Schedule holder", "Privacy Act/EO 12333 compliance framework"]),
    naicsCode: "541519",
    setAside: "Unrestricted",
    valueMin: 5000000,
    valueMax: 20000000,
    dueDate: new Date("2026-09-10"),
    pob: "Nationwide",
    securityClear: "Secret",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0008",
    title: "Legacy Application Modernization — COBOL to Cloud Migration",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service",
    description: "Legacy COBOL and mainframe application modernization to cloud-native microservices architecture under GSA Alliant 3 for large entitlement benefit programs. Project includes automated code refactoring, strangler fig migration pattern, and parallel-run validation.",
    requirements: JSON.stringify(["Alliant 3 contract holder", "COBOL/PL1 mainframe expertise", "Cloud-native microservices migration", "Zero-downtime cutover methodology"]),
    naicsCode: "541511",
    setAside: "Unrestricted",
    valueMin: 40000000,
    valueMax: 100000000,
    dueDate: new Date("2026-08-20"),
    pob: "Washington, DC (Hybrid)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0009",
    title: "Geospatial Platform Support — Federal GIS Shared Services",
    agency: "General Services Administration",
    subAgency: "Technology Transformation Services",
    description: "Federal geospatial platform shared services through GSA MAS providing ArcGIS Enterprise hosting, GIS data management, geospatial app development, and national datasets maintenance for civilian agency customers.",
    requirements: JSON.stringify(["Esri Enterprise GIS expertise", "FedRAMP ArcGIS deployment experience", "GSA MAS SIN 54151GEO", "Federal geospatial data standards"]),
    naicsCode: "541370",
    setAside: "8(a)",
    valueMin: 8000000,
    valueMax: 22000000,
    dueDate: new Date("2026-07-10"),
    pob: "Washington, DC / Remote",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0009",
    title: "IT Training & Change Management — Federal Workforce Upskilling",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — Human Capital Category",
    description: "Government-wide IT workforce upskilling and change management services under GSA OASIS+ covering cloud computing certifications, cybersecurity awareness training, digital transformation change management, and learning management system operations.",
    requirements: JSON.stringify(["OASIS+ contract holder", "Federal workforce development experience", "LMS hosting and administration", "OPM competency framework alignment"]),
    naicsCode: "611430",
    setAside: "SDVOSB",
    valueMin: 12000000,
    valueMax: 35000000,
    dueDate: new Date("2026-06-05"),
    pob: "Nationwide (Primarily Remote)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0010",
    title: "Software Asset Management & License Optimization Services",
    agency: "General Services Administration",
    subAgency: "Government-wide Acquisition — Software Category",
    description: "Enterprise software asset management, license compliance, and optimization services through GSA MAS helping federal agencies right-size enterprise software spend across Microsoft, Oracle, SAP, Adobe, and other major vendors.",
    requirements: JSON.stringify(["SAM tool expertise (Snow/Flexera/ServiceNow SAM)", "Federal enterprise licensing knowledge", "GSA MAS holder", "Category management methodology"]),
    naicsCode: "541519",
    setAside: "SB",
    valueMin: 4000000,
    valueMax: 12000000,
    dueDate: new Date("2026-08-05"),
    pob: "Nationwide (Remote-Capable)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0010",
    title: "Contact Center Modernization — Omnichannel Citizen Experience",
    agency: "General Services Administration",
    subAgency: "Customer Experience Center of Excellence",
    description: "Federal contact center modernization under GSA OASIS+ transforming legacy call center operations to omnichannel citizen experience platforms with AI chatbots, intelligent routing, quality monitoring, and CX analytics.",
    requirements: JSON.stringify(["OASIS+ contract holder", "CCaaS federal implementation (Amazon Connect/Genesys)", "AI chatbot integration experience", "CX measurement and analytics"]),
    naicsCode: "561422",
    setAside: "Unrestricted",
    valueMin: 18000000,
    valueMax: 50000000,
    dueDate: new Date("2026-07-25"),
    pob: "Washington, DC / Remote",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0011",
    title: "Quantum Computing Readiness Assessment — Federal Agencies",
    agency: "General Services Administration",
    subAgency: "Office of Government-wide Policy",
    description: "Post-quantum cryptography readiness assessment and migration planning services through GSA MAS for civilian agencies implementing NIST PQC standards. Services include cryptographic inventory, algorithm migration roadmaps, and hybrid encryption implementation.",
    requirements: JSON.stringify(["Post-quantum cryptography expertise", "NIST PQC standard implementation", "Federal cryptographic policy knowledge", "GSA MAS Schedule holder"]),
    naicsCode: "541519",
    setAside: "Unrestricted",
    valueMin: 3000000,
    valueMax: 10000000,
    dueDate: new Date("2026-09-20"),
    pob: "Washington, DC",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0011",
    title: "Application Security Testing & DevSecOps Pipeline Services",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — IT Security Category",
    description: "Application security testing and DevSecOps pipeline integration services under GSA Alliant 3 covering SAST, DAST, SCA, penetration testing, and secure software supply chain services for federal development programs.",
    requirements: JSON.stringify(["Alliant 3 contract holder", "SAST/DAST/SCA tool expertise", "Federal pen testing authorization (RMF)", "SBOM generation and management"]),
    naicsCode: "541512",
    setAside: "SB",
    valueMin: 8000000,
    valueMax: 25000000,
    dueDate: new Date("2026-06-15"),
    pob: "Nationwide (Remote-Capable)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0012",
    title: "Federal Building Smart Technology Integration",
    agency: "General Services Administration",
    subAgency: "Public Buildings Service — Technology Programs",
    description: "Smart building technology integration for GSA-managed federal facilities through MAS covering IoT sensors, building automation systems, energy management, occupancy analytics, and digital twin deployment to optimize federal real estate utilization.",
    requirements: JSON.stringify(["Smart building IoT deployment", "BAS/BMS integration experience", "GSA PBS security requirements", "Energy Star certification alignment"]),
    naicsCode: "238210",
    setAside: "WOSB",
    valueMin: 10000000,
    valueMax: 30000000,
    dueDate: new Date("2026-08-25"),
    pob: "Multiple GSA-Managed Federal Buildings",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "47QRAA26R0012",
    title: "Disaster Recovery & Business Continuity as a Service",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — Cloud Solutions",
    description: "Disaster recovery and business continuity as a service under GSA Alliant 3 providing cloud-based DR testing, automated failover, backup management, and COOP plan support for mission-critical federal systems with RTO less than 4 hours.",
    requirements: JSON.stringify(["Alliant 3 contract holder", "Federal COOP/DR planning experience", "Cloud DR automation (AWS/Azure Backup)", "FISMA impact level coverage (Moderate/High)"]),
    naicsCode: "541519",
    setAside: "HUBZone",
    valueMin: 15000000,
    valueMax: 45000000,
    dueDate: new Date("2026-07-05"),
    pob: "Nationwide (Multi-Region Cloud)",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
  {
    solicNumber: "GS-35F-26R-0013",
    title: "Data Center Optimization & Consolidation Services",
    agency: "General Services Administration",
    subAgency: "Federal Acquisition Service — Data Center Optimization Initiative",
    description: "Federal data center optimization and consolidation advisory services through GSA MAS supporting OMB DCOI compliance including data center closures, server virtualization, power usage effectiveness improvement, and cloud migration strategy.",
    requirements: JSON.stringify(["DCOI compliance expertise", "Federal data center assessment", "GSA MAS Schedule holder", "PUE optimization engineering"]),
    naicsCode: "541519",
    setAside: "8(a)",
    valueMin: 5000000,
    valueMax: 15000000,
    dueDate: new Date("2026-06-20"),
    pob: "Washington, DC / Field Data Centers",
    securityClear: "None",
    type: "GSA",
    vehicleType: "GSA",
  },
];

const sbirContracts = [
  {
    solicNumber: "AF-SBIR-26-0001",
    title: "Additive Manufacturing for Hypersonic Thermal Protection Components",
    agency: "Department of the Air Force",
    subAgency: "Air Force Research Laboratory — Materials & Manufacturing Directorate",
    description: "Phase II SBIR for small business development of additive manufacturing processes for ultra-high-temperature ceramic (UHTC) hypersonic thermal protection components. Performer shall demonstrate print-to-part dimensional accuracy and flexural strength exceeding baseline machined UHTC by 15%.",
    requirements: JSON.stringify(["Phase I SBIR success in UHTC materials", "Additive manufacturing of ceramics (binder jet/DED)", "ITAR-compliant facility", "Small business certification required"]),
    naicsCode: "541715",
    setAside: "SB",
    valueMin: 750000,
    valueMax: 1750000,
    dueDate: new Date("2026-06-15"),
    pob: "Dayton, OH / Wright-Patterson AFB, OH",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "AF-SBIR-26-0002",
    title: "AI-Enabled Electronic Warfare Threat Library Automation",
    agency: "Department of the Air Force",
    subAgency: "Air Force Life Cycle Management Center — Electronic Warfare Division",
    description: "Phase II SBIR for automated machine learning pipeline that ingests multi-INT sensor data and autonomously generates and validates electronic warfare threat emitter models, reducing manual library update timelines from months to days.",
    requirements: JSON.stringify(["ML signal processing expertise", "EW threat library management background", "TS/SCI clearance required", "SBIR Phase I completion"]),
    naicsCode: "541519",
    setAside: "SB",
    valueMin: 1000000,
    valueMax: 2000000,
    dueDate: new Date("2026-07-01"),
    pob: "Wright-Patterson AFB, OH (On-Site Required)",
    securityClear: "TS/SCI",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "A-SBIR-26-0001",
    title: "Photonic Integrated Circuit Optical Gyroscope for GPS-Denied Navigation",
    agency: "Department of the Army",
    subAgency: "Army Research Office",
    description: "Phase I SBIR seeking novel photonic integrated circuit implementation of optical gyroscope achieving navigation-grade performance in a chip-scale form factor for dismounted soldier and small UAS applications in GPS-denied environments.",
    requirements: JSON.stringify(["Photonic integrated circuit design", "Inertial navigation metrology", "Small business status required", "DARPA/ONR research background preferred"]),
    naicsCode: "334511",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-06-30"),
    pob: "Performer Site",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "N-SBIR-26-0001",
    title: "Biodegradable Underwater Sensor Network for Mine Countermeasures",
    agency: "Department of the Navy",
    subAgency: "Office of Naval Research",
    description: "Phase II SBIR for biodegradable, self-powered acoustic sensor nodes that form an ad-hoc mesh network for mine detection and environmental monitoring in littoral zones. Sensors shall dissolve within 30 days of mission completion to avoid environmental hazard.",
    requirements: JSON.stringify(["Biodegradable electronics fabrication", "Underwater acoustic sensor design", "Marine environmental compliance", "Phase I SBIR completion verified"]),
    naicsCode: "334511",
    setAside: "SB",
    valueMin: 800000,
    valueMax: 1600000,
    dueDate: new Date("2026-07-15"),
    pob: "Performer Site / Narragansett Bay Test Site",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "AF-SBIR-26-0003",
    title: "Compact High-Power Microwave Weapon Subsystem",
    agency: "Department of the Air Force",
    subAgency: "Air Force Research Laboratory — Directed Energy Directorate",
    description: "Phase II SBIR for compact, vehicle-mountable high-power microwave source achieving 100 kW peak power in a sub-cubic-meter form factor for counter-electronics and counter-drone applications. Performer shall demonstrate 10,000-shot operational lifetime.",
    requirements: JSON.stringify(["High-power microwave source development", "Power electronics for DE systems", "SECRET clearance minimum", "DE safety protocols"]),
    naicsCode: "334515",
    setAside: "SB",
    valueMin: 1500000,
    valueMax: 2500000,
    dueDate: new Date("2026-08-01"),
    pob: "Kirtland AFB, NM",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "A-SBIR-26-0002",
    title: "Microfluidic Lab-on-Chip for Battlefield Chemical Agent Detection",
    agency: "Department of the Army",
    subAgency: "Army DEVCOM Chemical & Biological Center",
    description: "Phase I SBIR for microfluidic lab-on-chip biosensor capable of simultaneous detection of nerve agent metabolites, vesicant hydrolysis products, and blood agents in blood or urine specimens within 5 minutes at point-of-care.",
    requirements: JSON.stringify(["Microfluidics/lab-on-chip design", "Chemical agent biosensor expertise", "BSL-2 laboratory capability", "FDA EUA pathway understanding"]),
    naicsCode: "334516",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-06-10"),
    pob: "Performer Site / Edgewood, MD",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "N-SBIR-26-0002",
    title: "Distributed Fiber Optic Intrusion Detection for Submarine Infrastructure",
    agency: "Department of the Navy",
    subAgency: "Naval Facilities Engineering Systems Command",
    description: "Phase II SBIR for distributed fiber optic sensing system detecting and geolocating intrusion events along submarine cables and undersea infrastructure with less than 10m positional accuracy at ranges up to 100km without powered repeaters.",
    requirements: JSON.stringify(["Distributed fiber optic sensing (BOTDR/OTDR)", "Signal processing for acoustic events", "Marine environment qualification", "NAVFAC relationship preferred"]),
    naicsCode: "334220",
    setAside: "SB",
    valueMin: 700000,
    valueMax: 1500000,
    dueDate: new Date("2026-07-20"),
    pob: "Performer Site / Port Hueneme, CA",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "AF-SBIR-26-0004",
    title: "Neuromorphic Computing for Onboard SAR Image Processing",
    agency: "Department of the Air Force",
    subAgency: "Air Force Research Laboratory — Sensors Directorate",
    description: "Phase I SBIR for neuromorphic processor implementation of synthetic aperture radar image formation and change detection algorithms achieving real-time processing at fraction of the SWaP of current GPU-based solutions on airborne ISR platforms.",
    requirements: JSON.stringify(["Neuromorphic computing architecture", "SAR signal processing algorithms", "SWaP-constrained embedded systems", "FPGA/ASIC design capability"]),
    naicsCode: "334413",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-09-01"),
    pob: "Performer Site / Rome, NY",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "A-SBIR-26-0003",
    title: "Self-Healing Polymer Composite for Armored Vehicle Structure",
    agency: "Department of the Army",
    subAgency: "Army Research Laboratory — Vehicle Technology Directorate",
    description: "Phase II SBIR for intrinsic self-healing polymer composite structural material capable of recovering 90% of original tensile strength after ballistic impact damage without external intervention. Demonstrates path to scaled production for vehicle hull panels.",
    requirements: JSON.stringify(["Self-healing polymer chemistry", "Structural composite fabrication", "Ballistic testing capability (MIL-STD)", "Phase I SBIR completion required"]),
    naicsCode: "325211",
    setAside: "SB",
    valueMin: 900000,
    valueMax: 1800000,
    dueDate: new Date("2026-06-25"),
    pob: "Performer Site",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "N-SBIR-26-0003",
    title: "Quantum Magnetometer for Submarine Anomaly Detection",
    agency: "Department of the Navy",
    subAgency: "Naval Research Laboratory",
    description: "Phase I SBIR for atomic magnetometer with sub-femtotesla sensitivity for submarine magnetic anomaly detection at extended standoff ranges. Performer shall characterize sensitivity in simulated ocean noise environment and propose vehicle integration path.",
    requirements: JSON.stringify(["Atomic/quantum magnetometry", "NRL collaboration history preferred", "Magnetic anomaly detection physics", "Cryogenic or room-temperature operation"]),
    naicsCode: "334516",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-07-30"),
    pob: "Performer Site / Washington, DC",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "AF-SBIR-26-0005",
    title: "3D-Printed Solid Rocket Motor Case for Tactical Missiles",
    agency: "Department of the Air Force",
    subAgency: "Air Force Research Laboratory — Aerospace Systems Directorate",
    description: "Phase II SBIR developing additively manufactured composite solid rocket motor case for tactical missiles with burst pressure exceeding MIL-specification at 20% cost reduction versus filament-wound cases and 6-week lead time.",
    requirements: JSON.stringify(["Composite rocket motor case manufacturing", "Additive manufacturing of structural composites", "Propulsion system qualification", "ITAR facility certification"]),
    naicsCode: "336415",
    setAside: "SB",
    valueMin: 1200000,
    valueMax: 2000000,
    dueDate: new Date("2026-08-15"),
    pob: "Edwards AFB, CA",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "A-SBIR-26-0004",
    title: "Implantable Neural Interface for Prosthetic Limb Control — Wounded Warrior",
    agency: "Department of the Army",
    subAgency: "Army Medical Research & Development Command",
    description: "Phase II SBIR for fully implantable neural interface decoder enabling intuitive multi-DOF control of prosthetic limbs through peripheral nerve signals. Performer shall complete IND application and initiate first-in-human pilot study with wounded warrior volunteers.",
    requirements: JSON.stringify(["Neural interface/BMI development", "FDA IND/IDE regulatory pathway", "Clinical research coordination", "Biocompatible implant design"]),
    naicsCode: "339113",
    setAside: "SB",
    valueMin: 1500000,
    valueMax: 3000000,
    dueDate: new Date("2026-06-20"),
    pob: "Performer Site / Walter Reed NMMC",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "N-SBIR-26-0004",
    title: "Solid-State Battery for Unmanned Underwater Vehicles",
    agency: "Department of the Navy",
    subAgency: "Naval Undersea Warfare Center",
    description: "Phase I SBIR for solid-state lithium battery achieving high energy density with zero thermal runaway risk for UUV applications. Battery must withstand 600m depth hydrostatic pressure and deliver rated capacity at 4°C ocean temperature.",
    requirements: JSON.stringify(["Solid-state battery development", "High energy density cell design", "Pressure vessel integration", "UUV power system knowledge"]),
    naicsCode: "335911",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-07-10"),
    pob: "Performer Site / Newport, RI",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "AF-SBIR-26-0006",
    title: "Photovoltaic-Thermal Dual-Use Solar Panel for Airbase Power",
    agency: "Department of the Air Force",
    subAgency: "Air Force Civil Engineer Center — Energy Directorate",
    description: "Phase II SBIR for combined photovoltaic-thermal solar panel achieving more than 30% total energy conversion efficiency while generating both electricity and thermal energy for airbase HVAC. Panel shall meet MIL-STD-810 for hail, humidity, and sand/dust.",
    requirements: JSON.stringify(["PVT solar panel development", "Military facility energy systems", "MIL-STD environmental qualification", "AFCEC energy program familiarity"]),
    naicsCode: "335999",
    setAside: "SB",
    valueMin: 1000000,
    valueMax: 2000000,
    dueDate: new Date("2026-09-10"),
    pob: "Tyndall AFB, FL",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "A-SBIR-26-0005",
    title: "Wearable Sweat Biomarker Monitor for Cognitive Load Assessment",
    agency: "Department of the Army",
    subAgency: "Army Research Laboratory — Human Research & Engineering Directorate",
    description: "Phase I SBIR for non-invasive wearable sensor array measuring cortisol, alpha-amylase, and neuropeptide Y in sweat as real-time biomarkers of soldier cognitive load and stress. Sensor shall operate continuously for 72 hours on standard Army batteries.",
    requirements: JSON.stringify(["Electrochemical biosensor development", "Wearable form factor integration", "Human factors validation methodology", "IRB-compliant study design"]),
    naicsCode: "334510",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-07-25"),
    pob: "Performer Site / Aberdeen Proving Ground, MD",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "N-SBIR-26-0005",
    title: "Adaptive Optics System for Shipboard Directed Energy Weapons",
    agency: "Department of the Navy",
    subAgency: "Office of Naval Research — Sea Warfare & Weapons Department",
    description: "Phase II SBIR for compact, rapid-update adaptive optics system correcting atmospheric turbulence effects for shipboard high-energy laser weapons at 100 kW power level. System shall maintain Strehl ratio above 0.8 in Beaufort Sea State 3.",
    requirements: JSON.stringify(["Adaptive optics wavefront correction", "High-power laser beam control", "Maritime platform qualification", "Phase I SBIR success required"]),
    naicsCode: "334511",
    setAside: "SB",
    valueMin: 1000000,
    valueMax: 2000000,
    dueDate: new Date("2026-08-20"),
    pob: "Dahlgren, VA / San Diego, CA",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "AF-SBIR-26-0007",
    title: "Quantum Radar Prototype for Low-Observable Target Detection",
    agency: "Department of the Air Force",
    subAgency: "Air Force Research Laboratory — Radar Sensing Directorate",
    description: "Phase I SBIR for quantum illumination radar protocol achieving quantum advantage in detecting low-observable targets in high-clutter environments. Performer shall demonstrate quantum correlator hardware and characterize sensitivity improvement versus classical radar in controlled laboratory.",
    requirements: JSON.stringify(["Quantum optics/microwave entanglement", "Radar signal processing background", "Quantum hardware fabrication", "TS/SCI clearance required"]),
    naicsCode: "334511",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-06-05"),
    pob: "Performer Site / Rome, NY",
    securityClear: "TS/SCI",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "A-SBIR-26-0006",
    title: "Exothermic Nanocomposite Reactive Material for Enhanced Warheads",
    agency: "Department of the Army",
    subAgency: "Army DEVCOM Armaments Center",
    description: "Phase II SBIR for energetic nanocomposite reactive material achieving 3x blast-thermal energy output of current shaped charge liners for anti-armor warhead applications. Performer shall produce 50 engineering prototype liners for live-fire lethality evaluation at APG.",
    requirements: JSON.stringify(["Energetic materials chemistry", "Nanocomposite synthesis", "Live-fire safety officer qualification", "TS/SCI for some aspects"]),
    naicsCode: "325920",
    setAside: "SB",
    valueMin: 2000000,
    valueMax: 3500000,
    dueDate: new Date("2026-08-10"),
    pob: "Picatinny Arsenal, NJ",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "N-SBIR-26-0006",
    title: "Machine Learning Hull Form Optimization for Naval Surface Combatants",
    agency: "Department of the Navy",
    subAgency: "Naval Surface Warfare Center — Carderock Division",
    description: "Phase I SBIR applying generative design and ML surrogate modeling to naval surface combatant hull form optimization targeting 15% fuel consumption reduction at 18-knot transit speed while maintaining stealth and seakeeping requirements.",
    requirements: JSON.stringify(["Computational fluid dynamics for naval vessels", "ML surrogate model development", "NSRDC tow tank test experience preferred", "Naval architecture background"]),
    naicsCode: "541330",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-07-05"),
    pob: "Performer Site / Bethesda, MD",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "AF-SBIR-26-0008",
    title: "Autonomous Satellite Servicing Rendezvous Navigation Software",
    agency: "Department of the Air Force",
    subAgency: "Space Systems Command — Space Domain Awareness Programs",
    description: "Phase II SBIR for autonomous relative navigation and proximity operations software enabling a servicer satellite to rendezvous with and inspect uncooperative resident space objects. Software must demonstrate safe operation within 10m of target in hardware-in-the-loop simulation.",
    requirements: JSON.stringify(["Autonomous rendezvous & proximity operations", "Vision-based relative navigation", "Space safety (conjunction analysis)", "SECRET clearance preferred"]),
    naicsCode: "541715",
    setAside: "SB",
    valueMin: 1250000,
    valueMax: 2500000,
    dueDate: new Date("2026-09-15"),
    pob: "El Segundo, CA",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "A-SBIR-26-0007",
    title: "Gallium Nitride Power Amplifier for Army Software-Defined Radio",
    agency: "Department of the Army",
    subAgency: "Program Executive Office Command, Control, Communications-Tactical",
    description: "Phase II SBIR for wide-bandgap GaN MMIC power amplifier achieving 100W output power across 20MHz-6GHz with high power-added efficiency for Army mid-tier radio networks. Amplifier must withstand MIL-STD-461 EMI environment of armored vehicle.",
    requirements: JSON.stringify(["GaN MMIC design & fabrication", "Wideband amplifier for military radio", "ITAR compound semiconductor facility", "Phase I SBIR required"]),
    naicsCode: "334413",
    setAside: "SB",
    valueMin: 1000000,
    valueMax: 2000000,
    dueDate: new Date("2026-08-05"),
    pob: "Performer Site / Aberdeen Proving Ground, MD",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "N-SBIR-26-0007",
    title: "AI-Driven Predictive Maintenance for Naval Gas Turbines",
    agency: "Department of the Navy",
    subAgency: "Naval Sea Systems Command — Propulsion & Power Engineering",
    description: "Phase II SBIR for AI-driven predictive maintenance system for LM2500 marine gas turbine engines using real-time vibration, temperature, and oil analysis data to predict component failures 500+ hours in advance with low false alarm rate.",
    requirements: JSON.stringify(["Industrial AI predictive maintenance", "LM2500/gas turbine physics knowledge", "NAVSEA integration requirements", "Phase I SBIR completion"]),
    naicsCode: "541715",
    setAside: "SB",
    valueMin: 800000,
    valueMax: 1600000,
    dueDate: new Date("2026-07-20"),
    pob: "Performer Site / Philadelphia, PA",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "AF-SBIR-26-0009",
    title: "Stretchable Electronics for Conformable Antenna in Uniforms",
    agency: "Department of the Air Force",
    subAgency: "Air Force Research Laboratory — Human Effectiveness Directorate",
    description: "Phase I SBIR for stretchable, washable antenna array integrated into combat uniform fabric operating at L/S-band for soldier communications. Antenna must not degrade soldier comfort or freedom of movement and survive 10,000+ wash cycles.",
    requirements: JSON.stringify(["Stretchable electronics fabrication", "Textile-integrated antenna design", "Military uniform material compatibility", "Human factors testing capability"]),
    naicsCode: "334220",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-06-20"),
    pob: "Performer Site / Wright-Patterson AFB, OH",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "A-SBIR-26-0008",
    title: "Biodegradable Area Denial Munition for Contested Terrain",
    agency: "Department of the Army",
    subAgency: "Army DEVCOM Armaments Center",
    description: "Phase II SBIR for biodegradable, self-neutralizing area denial munition that degrades to non-hazardous byproducts within 30 days post-activation-window. Munition shall achieve 90% area coverage effectiveness in 250m radius during active window.",
    requirements: JSON.stringify(["Munitions design and safety qualification", "Biodegradable energetic materials", "Environmental compliance analysis", "Live-fire safety officer"]),
    naicsCode: "332993",
    setAside: "SB",
    valueMin: 1800000,
    valueMax: 3200000,
    dueDate: new Date("2026-09-05"),
    pob: "Picatinny Arsenal, NJ / Dugway Proving Ground, UT",
    securityClear: "Secret",
    type: "SBIR",
    vehicleType: "SBIR",
  },
  {
    solicNumber: "N-SBIR-26-0008",
    title: "Low-Power Acoustic Modem for Long-Duration AUV Swarms",
    agency: "Department of the Navy",
    subAgency: "Naval Undersea Warfare Center — Newport Division",
    description: "Phase I SBIR for ultra-low-power acoustic modem achieving 10kbps data rate at 10km range consuming less than 1W average power for long-endurance AUV swarm coordination. Modem must operate without surfacing across 30-day mission durations in deep ocean noise environment.",
    requirements: JSON.stringify(["Underwater acoustic communications", "Ultra-low-power modem design", "AUV integration experience", "NUWC Newport relationship"]),
    naicsCode: "334220",
    setAside: "SB",
    valueMin: 150000,
    valueMax: 300000,
    dueDate: new Date("2026-08-25"),
    pob: "Performer Site / Newport, RI",
    securityClear: "None",
    type: "SBIR",
    vehicleType: "SBIR",
  },
];

async function main() {
  const allContracts = [
    ...idiqContracts,
    ...otaContracts,
    ...gsaContracts,
    ...sbirContracts,
  ];

  let count = 0;
  for (const contract of allContracts) {
    await prisma.contract.upsert({
      where: { solicNumber: contract.solicNumber },
      update: {},
      create: {
        ...contract,
        postedDate: new Date(),
      },
    });
    count++;
  }

  console.log(`SEEDING COMPLETE: ${count} contracts inserted`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
